package main

import (
	"bytes"
	"crypto/md5"
	"encoding/hex"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Nested packages under assert/ that must ship with the embedded module so
// materialize/cache layout resolves imports (legacy_v1, legacy_v2, …).
var nestedAssertPkgs = []string{"legacy_v1", "legacy_v2"}

func main() {
	out := flag.String("o", "", "output file path")
	cacheKeyOut := flag.String("cache-key", "", "optional Go file declaring raw-source cache key MD5")
	// Parent directory for nested packages (e.g. libdoc/assertmod), or the
	// historical path ending in legacy_v1 (parent is then used for all nested pkgs).
	legacyOut := flag.String("legacy-out", "", "parent dir for nested assert packages (legacy_v1, legacy_v2)")
	flag.Parse()
	if *out == "" || flag.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "usage: embed-assert -o <out> [-cache-key <go>] [-legacy-out <parentDir>] <assertDir>  (invoked via go run ./script/generate)")
		os.Exit(2)
	}
	if err := run(*out, *cacheKeyOut, *legacyOut, flag.Arg(0)); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(outPath, cacheKeyOut, legacyOutDir, assertDir string) error {
	names, err := listSourceFiles(assertDir)
	if err != nil {
		return err
	}

	rawHash := md5.New()
	var bodies []string
	imports := make(map[string]string)

	for _, name := range names {
		data, err := os.ReadFile(filepath.Join(assertDir, name))
		if err != nil {
			return err
		}
		if _, err := rawHash.Write(data); err != nil {
			return err
		}
		fileImports, body, err := splitImportsAndBody(name, data)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		for path, alias := range fileImports {
			if existing, ok := imports[path]; !ok || existing == "" {
				imports[path] = alias
			}
		}
		bodies = append(bodies, string(body))
	}

	nestedSources := make(map[string][]namedFile)
	for _, pkg := range nestedAssertPkgs {
		pkgDir := filepath.Join(assertDir, pkg)
		pkgNames, err := listSourceFiles(pkgDir)
		if err != nil {
			return fmt.Errorf("%s: %w", pkg, err)
		}
		var files []namedFile
		for _, name := range pkgNames {
			data, err := os.ReadFile(filepath.Join(pkgDir, name))
			if err != nil {
				return err
			}
			if _, err := rawHash.Write(data); err != nil {
				return err
			}
			files = append(files, namedFile{name: name, data: data})
		}
		nestedSources[pkg] = files
	}
	rawMD5 := hex.EncodeToString(rawHash.Sum(nil))

	var merged bytes.Buffer
	merged.WriteString("// Code generated by script/generate/embed-assert; DO NOT EDIT.\n\n")
	merged.WriteString("//go:build ignore\n\n")
	merged.WriteString("package assert\n\n")
	writeImportBlock(&merged, imports)
	for _, body := range bodies {
		trimmed := strings.TrimSpace(body)
		if trimmed == "" {
			continue
		}
		merged.WriteString(trimmed)
		merged.WriteString("\n\n")
	}

	formatted, err := format.Source(merged.Bytes())
	if err != nil {
		return fmt.Errorf("format merged source: %w", err)
	}
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		return err
	}

	if legacyOutDir != "" {
		parent := legacyOutDir
		// Historical flag value was .../legacy_v1; treat as parent of nested pkgs.
		if filepath.Base(parent) == "legacy_v1" {
			parent = filepath.Dir(parent)
		}
		for _, pkg := range nestedAssertPkgs {
			outDir := filepath.Join(parent, pkg)
			if err := os.MkdirAll(outDir, 0755); err != nil {
				return err
			}
			keep := make(map[string]bool, len(nestedSources[pkg]))
			for _, f := range nestedSources[pkg] {
				keep[f.name] = true
			}
			if entries, err := os.ReadDir(outDir); err == nil {
				for _, e := range entries {
					if !e.IsDir() && !keep[e.Name()] {
						_ = os.Remove(filepath.Join(outDir, e.Name()))
					}
				}
			}
			for _, f := range nestedSources[pkg] {
				if err := os.WriteFile(filepath.Join(outDir, f.name), f.data, 0644); err != nil {
					return err
				}
			}
		}
	}
	if cacheKeyOut != "" {
		src := fmt.Sprintf("// Code generated by script/generate/embed-assert; DO NOT EDIT.\n\npackage assertmod\n\nconst rawSourceCacheKeyMD5 = %q\n", rawMD5)
		if err := os.WriteFile(cacheKeyOut, []byte(src), 0644); err != nil {
			return err
		}
	}
	return nil
}

type namedFile struct {
	name string
	data []byte
}

func listSourceFiles(assertDir string) ([]string, error) {
	entries, err := os.ReadDir(assertDir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names, nil
}

func splitImportsAndBody(filename string, src []byte) (map[string]string, []byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.ParseComments)
	if err != nil {
		return nil, nil, err
	}

	imports := make(map[string]string)
	var lastDeclEnd token.Pos
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.IMPORT {
			break
		}
		for _, spec := range gen.Specs {
			imp, ok := spec.(*ast.ImportSpec)
			if !ok {
				continue
			}
			path := strings.Trim(imp.Path.Value, `"`)
			alias := ""
			if imp.Name != nil {
				alias = imp.Name.Name
			}
			imports[path] = alias
		}
		if gen.End() > lastDeclEnd {
			lastDeclEnd = gen.End()
		}
	}

	start := 0
	if lastDeclEnd > 0 {
		start = fset.Position(lastDeclEnd).Offset
	} else {
		start = fset.Position(file.Name.End()).Offset
	}
	body := bytes.TrimSpace(src[start:])
	return imports, body, nil
}

func writeImportBlock(buf *bytes.Buffer, imports map[string]string) {
	if len(imports) == 0 {
		return
	}
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	if len(paths) == 1 {
		path := paths[0]
		if alias := imports[path]; alias != "" {
			fmt.Fprintf(buf, "import %s %q\n\n", alias, path)
			return
		}
		fmt.Fprintf(buf, "import %q\n\n", path)
		return
	}

	buf.WriteString("import (\n")
	for _, path := range paths {
		if alias := imports[path]; alias != "" {
			fmt.Fprintf(buf, "\t%s %q\n", alias, path)
			continue
		}
		fmt.Fprintf(buf, "\t%q\n", path)
	}
	buf.WriteString(")\n\n")
}
