package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/xhd2015/doctest/libdoc/assertmod"
)

const AssertImportPath = "github.com/xhd2015/doctest/assert"

// CasesImportAssertPackage reports whether any case imports the doctest assert package.
func CasesImportAssertPackage(cases []TreeCase, modPath string) bool {
	_ = modPath
	for _, tc := range cases {
		imports := collectImports(tc.SetupFiles, tc.AssertFile.GoBlock)
		for _, spec := range imports {
			if spec.Path == AssertImportPath {
				return true
			}
		}
	}
	return false
}

// MaterializeAssertModule writes embedded assert sources to a content-addressed cache
// directory under $CACHE/doctest/assert-mod/<md5>/ and returns the cache path.
func MaterializeAssertModule() (string, error) {
	content := assertModuleSourceForCache()
	md5hex := assertmod.RawSourceCacheKeyMD5()

	cacheDir, err := os.UserCacheDir()
	if err != nil {
		return "", err
	}
	cacheRoot := filepath.Join(cacheDir, "doctest", "assert-mod", md5hex)

	if assertCacheLayoutComplete(cacheRoot) {
		return cacheRoot, nil
	}

	if err := os.MkdirAll(cacheRoot, 0755); err != nil {
		return "", err
	}

	assertGo := filepath.Join(cacheRoot, "assert.go")
	if !fileExists(assertGo) {
		if err := os.WriteFile(assertGo, content, 0644); err != nil {
			return "", err
		}
	}

	if err := materializeNestedPackage(cacheRoot, "legacy_v1", assertmod.LegacyV1Filenames, assertmod.LegacyV1File); err != nil {
		return "", err
	}
	if err := materializeNestedPackage(cacheRoot, "legacy_v2", assertmod.LegacyV2Filenames, assertmod.LegacyV2File); err != nil {
		return "", err
	}

	goMod := filepath.Join(cacheRoot, "go.mod")
	goModContent := fmt.Sprintf("module %s\n\ngo 1.18\n", AssertImportPath)
	if !fileExists(goMod) {
		if err := os.WriteFile(goMod, []byte(goModContent), 0644); err != nil {
			return "", err
		}
	}

	return cacheRoot, nil
}

func materializeNestedPackage(cacheRoot, pkg string, namesFn func() ([]string, error), fileFn func(string) ([]byte, error)) error {
	names, err := namesFn()
	if err != nil {
		return err
	}
	root := filepath.Join(cacheRoot, pkg)
	if err := os.MkdirAll(root, 0755); err != nil {
		return err
	}
	for _, name := range names {
		path := filepath.Join(root, name)
		if fileExists(path) {
			continue
		}
		data, err := fileFn(name)
		if err != nil {
			return err
		}
		if err := os.WriteFile(path, data, 0644); err != nil {
			return err
		}
	}
	return nil
}

func assertCacheLayoutComplete(cacheRoot string) bool {
	if !fileExists(filepath.Join(cacheRoot, "assert.go")) || !fileExists(filepath.Join(cacheRoot, "go.mod")) {
		return false
	}
	if !nestedPackageComplete(cacheRoot, "legacy_v1", assertmod.LegacyV1Filenames) {
		return false
	}
	if !nestedPackageComplete(cacheRoot, "legacy_v2", assertmod.LegacyV2Filenames) {
		return false
	}
	return true
}

func nestedPackageComplete(cacheRoot, pkg string, namesFn func() ([]string, error)) bool {
	names, err := namesFn()
	if err != nil {
		return false
	}
	for _, name := range names {
		if !fileExists(filepath.Join(cacheRoot, pkg, name)) {
			return false
		}
	}
	return true
}

func assertModuleSourceForCache() []byte {
	content := assertmod.Content()
	text := string(content)
	lines := strings.SplitAfter(text, "\n")
	i := 0
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" ||
			trimmed == "// Code generated by script/generate/embed-assert; DO NOT EDIT." ||
			trimmed == "//go:build ignore" {
			i++
			continue
		}
		break
	}
	return []byte(strings.Join(lines[i:], ""))
}

// WriteInternalModfile copies the parent go.mod and appends an assert replace directive.
func WriteInternalModfile(modRoot, assertCacheDir string) (string, error) {
	parentGoMod := filepath.Join(modRoot, "go.mod")
	data, err := os.ReadFile(parentGoMod)
	if err != nil {
		return "", err
	}
	content := string(data)
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += fmt.Sprintf("\nreplace %s => %s\n", AssertImportPath, assertCacheDir)

	modfilePath := filepath.Join(modRoot, ".doctest.mod")
	if err := os.WriteFile(modfilePath, []byte(content), 0644); err != nil {
		return "", err
	}
	return modfilePath, nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}