package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/xhd2015/doctest/libdoc/sessionmod"
)

const SessionImportPath = "github.com/xhd2015/doctest/session"

// CasesImportSessionPackage reports whether any case imports the doctest session package.
// Since P2, assemble always injects session.Doctest, so this is effectively always true
// for generation; kept for callers that still check author imports explicitly.
func CasesImportSessionPackage(cases []TreeCase, modPath string) bool {
	_ = modPath
	_ = cases
	return true
}

// MaterializeSessionModule writes embedded session sources to a content-addressed cache
// directory under $CACHE/doctest/session-mod/<md5>/ and returns the cache path.
func MaterializeSessionModule() (string, error) {
	content := sessionModuleSourceForCache()
	md5hex := sessionmod.RawSourceCacheKeyMD5()

	cacheDir, err := CacheHome()
	if err != nil {
		return "", err
	}
	cacheRoot := filepath.Join(cacheDir, "doctest", "session-mod", md5hex)

	if sessionCacheLayoutComplete(cacheRoot) {
		return cacheRoot, nil
	}

	if err := os.MkdirAll(cacheRoot, 0755); err != nil {
		return "", err
	}

	sessionGo := filepath.Join(cacheRoot, "session.go")
	if !fileExists(sessionGo) {
		if err := os.WriteFile(sessionGo, content, 0644); err != nil {
			return "", err
		}
	}

	goMod := filepath.Join(cacheRoot, "go.mod")
	goModContent := fmt.Sprintf("module %s\n\ngo 1.18\n", SessionImportPath)
	if !fileExists(goMod) {
		if err := os.WriteFile(goMod, []byte(goModContent), 0644); err != nil {
			return "", err
		}
	}

	return cacheRoot, nil
}

func sessionCacheLayoutComplete(cacheRoot string) bool {
	if !fileExists(filepath.Join(cacheRoot, "go.mod")) {
		return false
	}
	// At least one .go source (session.go or once.go style).
	entries, err := os.ReadDir(cacheRoot)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
			return true
		}
	}
	return false
}

func sessionModuleSourceForCache() []byte {
	content := sessionmod.Content()
	text := string(content)
	lines := strings.SplitAfter(text, "\n")
	i := 0
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" ||
			trimmed == "// Code generated by script/generate/embed-session; DO NOT EDIT." ||
			trimmed == "//go:build ignore" {
			i++
			continue
		}
		break
	}
	return []byte(strings.Join(lines[i:], ""))
}
