package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/xhd2015/doctest/libdoc/sessionmod"
	"golang.org/x/sys/unix"
)

const SessionImportPath = "github.com/xhd2015/doctest/session"

// sessionMaterializeMu serializes first-time writes within one process.
// Cross-process races use flock on cacheRoot+".lock" (nested doctest subprocesses).
var sessionMaterializeMu sync.Mutex

// CasesImportSessionPackage reports whether any case imports the doctest session package.
// Since P2, assemble always injects session.Doctest, so this is effectively always true
// for generation; kept for callers that still check author imports explicitly.
func CasesImportSessionPackage(cases []TreeCase, modPath string) bool {
	_ = modPath
	_ = cases
	return true
}

// MaterializeSessionModule writes embedded session sources to a content-addressed cache
// directory under $CACHE/doctest/session-mod/<md5>/ and returns the cache path.
// Safe for concurrent callers: cold path stages into a temp dir then renames into place.
// Cross-process safety: exclusive flock on <cacheRoot>.lock before writing.
func MaterializeSessionModule() (string, error) {
	content := sessionModuleSourceForCache()
	md5hex := sessionmod.RawSourceCacheKeyMD5()

	cacheDir, err := CacheHome()
	if err != nil {
		return "", err
	}
	cacheRoot := filepath.Join(cacheDir, "doctest", "session-mod", md5hex)

	if sessionCacheLayoutComplete(cacheRoot) {
		return cacheRoot, nil
	}

	sessionMaterializeMu.Lock()
	defer sessionMaterializeMu.Unlock()

	// Re-check under process lock (another leaf may have finished).
	if sessionCacheLayoutComplete(cacheRoot) {
		return cacheRoot, nil
	}

	parent := filepath.Dir(cacheRoot)
	if err := os.MkdirAll(parent, 0755); err != nil {
		return "", err
	}

	// Cross-process exclusive lock so parallel nested doctest binaries do not
	// observe a half-written session-mod (in-process mu alone is not enough).
	unlock, err := flockExclusive(cacheRoot + ".lock")
	if err != nil {
		return "", fmt.Errorf("session-mod flock: %w", err)
	}
	defer unlock()

	if sessionCacheLayoutComplete(cacheRoot) {
		return cacheRoot, nil
	}

	// Stage then rename so readers never see an incomplete session-mod dir.
	tmp, err := os.MkdirTemp(parent, "session-mod-stage-*")
	if err != nil {
		return "", err
	}
	staged := true
	defer func() {
		if staged {
			_ = os.RemoveAll(tmp)
		}
	}()

	sessionGo := filepath.Join(tmp, "session.go")
	if err := os.WriteFile(sessionGo, content, 0644); err != nil {
		return "", err
	}
	goMod := filepath.Join(tmp, "go.mod")
	goModContent := fmt.Sprintf("module %s\n\ngo 1.18\n", SessionImportPath)
	if err := os.WriteFile(goMod, []byte(goModContent), 0644); err != nil {
		return "", err
	}
	if !sessionCacheLayoutComplete(tmp) {
		return "", fmt.Errorf("session-mod stage incomplete: %s", tmp)
	}

	// If another process won the rename race, prefer the winner if complete.
	if err := os.Rename(tmp, cacheRoot); err != nil {
		if sessionCacheLayoutComplete(cacheRoot) {
			return cacheRoot, nil
		}
		// Windows / busy: fall back to copy-in-place under lock.
		if err := os.MkdirAll(cacheRoot, 0755); err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(cacheRoot, "session.go"), content, 0644); err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(cacheRoot, "go.mod"), []byte(goModContent), 0644); err != nil {
			return "", err
		}
	} else {
		// Ownership transferred to cacheRoot; do not RemoveAll(tmp).
		staged = false
	}

	if !sessionCacheLayoutComplete(cacheRoot) {
		return "", fmt.Errorf("session-mod materialize incomplete: %s", cacheRoot)
	}
	return cacheRoot, nil
}

// flockExclusive creates path if needed and takes an exclusive flock.
// Returns an unlock func (always safe to call).
func flockExclusive(path string) (unlock func(), err error) {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0644)
	if err != nil {
		return nil, err
	}
	if err := unix.Flock(int(f.Fd()), unix.LOCK_EX); err != nil {
		_ = f.Close()
		return nil, err
	}
	return func() {
		_ = unix.Flock(int(f.Fd()), unix.LOCK_UN)
		_ = f.Close()
	}, nil
}

func sessionCacheLayoutComplete(cacheRoot string) bool {
	if !fileExists(filepath.Join(cacheRoot, "go.mod")) {
		return false
	}
	// At least one .go source (session.go or once.go style).
	entries, err := os.ReadDir(cacheRoot)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
			return true
		}
	}
	return false
}

func sessionModuleSourceForCache() []byte {
	content := sessionmod.Content()
	text := string(content)
	lines := strings.SplitAfter(text, "\n")
	i := 0
	for i < len(lines) {
		trimmed := strings.TrimSpace(lines[i])
		if trimmed == "" ||
			trimmed == "// Code generated by script/generate/embed-session; DO NOT EDIT." ||
			trimmed == "//go:build ignore" {
			i++
			continue
		}
		break
	}
	return []byte(strings.Join(lines[i:], ""))
}
