// Code generated by script/generate/embed-assert; DO NOT EDIT.

//go:build ignore

package assert

import (
	"fmt"
	"github.com/xhd2015/doctest/assert/legacy_v1"
	"gopkg.in/yaml.v3"
	"regexp"
	"sort"
	"strings"
	"testing"
)

var namedColors = map[string]string{
	"bold":  "1",
	"red":   "31",
	"green": "32",
	"gray":  "90",
}

const (
	colorReset          = "\x1b[0m"
	ansiColorOpenPrefix = "<ansi-color"
	ansiColorCloseTag   = "</ansi-color>"
	ansiColorTagName    = "ansi-color"
)

func resolveColorOpen(spec colorSpec) (string, error) {
	var b strings.Builder
	for _, tok := range spec.Tokens {
		params, err := colorTokenParams(tok)
		if err != nil {
			return "", err
		}
		b.WriteString("\x1b[")
		b.WriteString(params)
		b.WriteString("m")
	}
	return b.String(), nil
}

func colorTokenParams(tok string) (string, error) {
	if strings.HasPrefix(tok, "#") {
		return tok[1:], nil
	}
	params, ok := namedColors[tok]
	if !ok {
		return "", parseErr(-1, "unknown color name %q; use # for raw SGR", tok)
	}
	return params, nil
}

func parseColorSpec(specText string) (colorSpec, error) {
	specText = strings.TrimSpace(specText)
	if specText == "" {
		return colorSpec{}, parseErr(-1, "empty ansi-color specifier")
	}
	var tokens []string
	for specText != "" {
		specText = strings.TrimLeft(specText, " \t")
		if specText == "" {
			break
		}
		if specText[0] == '#' {
			end := 1
			for end < len(specText) && specText[end] != ' ' && specText[end] != '\t' {
				end++
			}
			tokens = append(tokens, specText[:end])
			specText = specText[end:]
			continue
		}
		end := 0
		for end < len(specText) && specText[end] != ' ' && specText[end] != '\t' {
			end++
		}
		name := specText[:end]
		if _, ok := namedColors[name]; !ok {
			return colorSpec{}, parseErr(-1, "unknown color name %q", name)
		}
		tokens = append(tokens, name)
		specText = specText[end:]
	}
	return colorSpec{Tokens: tokens}, nil
}

type parseError struct {
	pos int
	msg string
}

func (e *parseError) Error() string {
	if e.pos >= 0 {
		return fmt.Sprintf("parse error at position %d: %s", e.pos, e.msg)
	}
	return fmt.Sprintf("parse error: %s", e.msg)
}

func parseErr(pos int, format string, args ...any) error {
	return &parseError{pos: pos, msg: fmt.Sprintf(format, args...)}
}

type matchError struct {
	msg string
}

func (e *matchError) Error() string {
	return e.msg
}

func matchErr(format string, args ...any) error {
	return &matchError{msg: fmt.Sprintf(format, args...)}
}

// Match compares actual output against pattern. nil means success.
func Match(p Pattern, actual string, opts ...Option) error {
	cfg := applyOptions(opts...)
	if p.v2 {
		if cfg.mode == matchContains {
			return matchErr("MatchContains is not supported for v2 templates")
		}
		return matchV2(p.v2pat, actual, cfg.normalizeNewlines)
	}
	return legacy_v1.Match(p.legacy, actual, legacy_v1.MatchConfig{
		Contains:          cfg.mode == matchContains,
		NormalizeNewlines: cfg.normalizeNewlines,
	})
}

type Option interface {
	apply(*matchConfig)
}

type matchConfig struct {
	mode              matchMode
	normalizeNewlines bool
}

type matchMode int

const (
	matchExact matchMode = iota
	matchContains
)

type containsOption struct{}

func (containsOption) apply(cfg *matchConfig) {
	cfg.mode = matchContains
}

// Contains enables MatchContains mode: the template must appear as a contiguous
// ordered subregion of actual output.
func Contains() Option {
	return containsOption{}
}

type normalizeNewlinesOption struct {
	v bool
}

func (o normalizeNewlinesOption) apply(cfg *matchConfig) {
	cfg.normalizeNewlines = o.v
}

// NormalizeNewlines controls \r\n → \n normalization (default true).
func NormalizeNewlines(v bool) Option {
	return normalizeNewlinesOption{v: v}
}

func defaultMatchConfig() matchConfig {
	return matchConfig{
		mode:              matchExact,
		normalizeNewlines: true,
	}
}

func applyOptions(opts ...Option) matchConfig {
	cfg := defaultMatchConfig()
	for _, o := range opts {
		o.apply(&cfg)
	}
	return cfg
}

// Output parses template, matches actual output, and calls t.Fatal on failure.
func Output(t *testing.T, actual, template string, opts ...Option) {
	t.Helper()
	p, err := Parse(template)
	if err != nil {
		t.Fatalf("parse output template: %v", err)
	}
	if err := Match(p, actual, opts...); err != nil {
		t.Fatal(err)
	}
}

// Parse parses template text into a Pattern.
func Parse(template string) (Pattern, error) {
	isV2, headerYAML, body, err := detectV2(template)
	if err != nil {
		return Pattern{}, err
	}
	if isV2 {
		v2pat, err := parseV2(headerYAML, body)
		if err != nil {
			return Pattern{}, err
		}
		return Pattern{v2: true, v2pat: v2pat}, nil
	}
	legacy, err := legacy_v1.Parse(template)
	if err != nil {
		return Pattern{}, err
	}
	return Pattern{v2: false, legacy: legacy}, nil
}

// MustParse parses template text or panics.
func MustParse(template string) Pattern {
	p, err := Parse(template)
	if err != nil {
		panic(err)
	}
	return p
}

// Pattern is an immutable parsed output template (v1 or v2).
type Pattern struct {
	v2     bool
	legacy legacy_v1.Pattern
	v2pat  v2Pattern
}

// PatternSummary returns a stable summary string for test introspection.
func PatternSummary(p Pattern) string {
	if p.v2 {
		return summaryV2(p.v2pat)
	}
	return legacy_v1.PatternSummary(p.legacy)
}

type v2Pattern struct {
	placeholders    map[string]v2Placeholder
	items           []v2Item
	trailingNewline bool
}

type v2Placeholder struct {
	Name     string
	Type     string
	Metadata map[string]string
}

type v2Item interface {
	isV2Item()
}

type v2LiteralLine struct {
	Text string
}

func (v2LiteralLine) isV2Item() {}

type v2PatternLine struct {
	Segments []v2Segment
}

func (v2PatternLine) isV2Item() {}

type v2RegexLine struct {
	Pattern string
}

func (v2RegexLine) isV2Item() {}

type v2OmitLine struct {
	Count int
}

func (v2OmitLine) isV2Item() {}

type v2Segment interface {
	isV2Segment()
}

type v2Literal struct {
	Text string
}

func (v2Literal) isV2Segment() {}

type v2PlaceholderRef struct {
	Name string
}

func (v2PlaceholderRef) isV2Segment() {}

type v2Color struct {
	Spec colorSpec
	Text string
}

func (v2Color) isV2Segment() {}

type colorSpec struct {
	Tokens []string
}

func matchV2(p v2Pattern, actual string, normalizeNewlines bool) error {
	if normalizeNewlines {
		actual = strings.ReplaceAll(actual, "\r\n", "\n")
	}
	if err := checkTrailingNewlineV2(p.trailingNewline, actual); err != nil {
		return err
	}
	lines := splitActualLinesV2(actual)
	cursor := 0
	for _, item := range p.items {
		n, err := matchV2Item(item, p.placeholders, lines, cursor, 0)
		if err != nil {
			return err
		}
		cursor = n
	}
	if cursor < len(lines) {
		return matchErr("unexpected extra output at line %d", cursor+1)
	}
	return nil
}

func checkTrailingNewlineV2(templateTrailing bool, actual string) error {
	actualTrailing := len(actual) > 0 && actual[len(actual)-1] == '\n'
	if templateTrailing != actualTrailing {
		return matchErr("output mismatch: trailing newline policy violated")
	}
	return nil
}

func splitActualLinesV2(actual string) []string {
	if actual == "" {
		return nil
	}
	body := strings.TrimSuffix(actual, "\n")
	if body == "" && strings.HasSuffix(actual, "\n") {
		return []string{""}
	}
	return strings.Split(body, "\n")
}

func matchV2Item(item v2Item, placeholders map[string]v2Placeholder, lines []string, cursor, lineBase int) (int, error) {
	switch it := item.(type) {
	case v2LiteralLine:
		return matchV2LiteralLine(it.Text, lines, cursor, lineBase)
	case v2PatternLine:
		return matchV2PatternLine(it, placeholders, lines, cursor, lineBase)
	case v2RegexLine:
		return matchV2RegexLine(it.Pattern, lines, cursor, lineBase)
	case v2OmitLine:
		return matchV2OmitLine(it.Count, lines, cursor, lineBase)
	default:
		return cursor, matchErr("internal error: unknown v2 item type")
	}
}

func matchV2LiteralLine(want string, lines []string, cursor, lineBase int) (int, error) {
	if cursor >= len(lines) {
		return cursor, matchErr("output mismatch at line %d:\n  want: %q\n  got:  (end of output)", lineBase+cursor+1, want)
	}
	got := lines[cursor]
	if got != want {
		return cursor, matchErr("output mismatch at line %d:\n  want: %q\n  got:  %q", lineBase+cursor+1, want, got)
	}
	return cursor + 1, nil
}

func matchV2PatternLine(pl v2PatternLine, placeholders map[string]v2Placeholder, lines []string, cursor, lineBase int) (int, error) {
	if cursor >= len(lines) {
		return cursor, matchErr("output mismatch at line %d: unexpected end of output", lineBase+cursor+1)
	}
	line := lines[cursor]
	// Match the whole line as one regex built from segments. Segment-by-segment
	// matching of type=string used `^[^\n]*?` alone, which always matches the
	// empty string (non-greedy with no trailing constraint). Anchoring with $
	// lets non-greedy string placeholders expand correctly mid-line and at EOL.
	reBody, err := buildPatternLineRegexFromSegments(pl.Segments, placeholders)
	if err != nil {
		return cursor, err
	}
	re, err := regexp.Compile("^" + reBody + "$")
	if err != nil {
		return cursor, matchErr("internal error: invalid pattern line regex: %v", err)
	}
	if !re.MatchString(line) {
		// Fall back to sequential diagnostics for a more precise error message.
		if _, segErr := matchV2Segments(pl.Segments, placeholders, line, lineBase+cursor+1); segErr != nil {
			return cursor, segErr
		}
		return cursor, matchErr("output mismatch at line %d:\n  pattern did not match %q", lineBase+cursor+1, line)
	}
	return cursor + 1, nil
}

// buildPatternLineRegexFromSegments joins segment patterns into a single-line RE.
// Literals are quoted; placeholders use placeholderSubpattern (string is non-greedy).
func buildPatternLineRegexFromSegments(segs []v2Segment, placeholders map[string]v2Placeholder) (string, error) {
	var b strings.Builder
	for _, seg := range segs {
		switch s := seg.(type) {
		case v2Literal:
			b.WriteString(regexp.QuoteMeta(s.Text))
		case v2PlaceholderRef:
			ph, ok := findPlaceholder(placeholders, s.Name)
			if !ok {
				return "", matchErr("internal error: undefined placeholder %s", s.Name)
			}
			sub, err := placeholderSubpattern(ph.Type)
			if err != nil {
				return "", err
			}
			b.WriteString("(?:")
			b.WriteString(sub)
			b.WriteString(")")
		case v2Color:
			open, err := resolveColorOpen(s.Spec)
			if err != nil {
				return "", err
			}
			b.WriteString(regexp.QuoteMeta(open + s.Text + colorReset))
		default:
			return "", matchErr("internal error: unknown v2 segment type")
		}
	}
	return b.String(), nil
}

func matchV2RegexLine(pattern string, lines []string, cursor, lineBase int) (int, error) {
	if cursor >= len(lines) {
		return cursor, matchErr("output mismatch at line %d: regex expected a line", lineBase+cursor+1)
	}
	re := regexp.MustCompile(pattern)
	if !re.MatchString(lines[cursor]) {
		return cursor, matchErr("output mismatch at line %d:\n  regex %q did not match %q", lineBase+cursor+1, pattern, lines[cursor])
	}
	return cursor + 1, nil
}

func matchV2OmitLine(count int, lines []string, cursor, lineBase int) (int, error) {
	if cursor+count > len(lines) {
		return cursor, matchErr("output mismatch at line %d: omit expected %d lines, got %d", lineBase+cursor+1, count, len(lines)-cursor)
	}
	return cursor + count, nil
}

func matchV2Segments(segs []v2Segment, placeholders map[string]v2Placeholder, line string, lineNo int) (string, error) {
	rest := line
	for _, seg := range segs {
		var err error
		rest, err = matchV2Segment(seg, placeholders, rest, lineNo)
		if err != nil {
			return rest, err
		}
	}
	return rest, nil
}

func matchV2Segment(seg v2Segment, placeholders map[string]v2Placeholder, line string, lineNo int) (string, error) {
	switch s := seg.(type) {
	case v2Literal:
		if !strings.HasPrefix(line, s.Text) {
			return line, matchErr("output mismatch at line %d:\n  want prefix: %q\n  got:         %q", lineNo, s.Text, line)
		}
		return line[len(s.Text):], nil
	case v2PlaceholderRef:
		ph, ok := findPlaceholder(placeholders, s.Name)
		if !ok {
			return line, matchErr("internal error: undefined placeholder %s", s.Name)
		}
		sub, err := placeholderSubpattern(ph.Type)
		if err != nil {
			return line, err
		}
		re := regexp.MustCompile("^" + sub)
		loc := re.FindStringIndex(line)
		if loc == nil || loc[0] != 0 {
			return line, matchErr("output mismatch at line %d:\n  placeholder __%s__ (%s) did not match %q", lineNo, s.Name, ph.Type, line)
		}
		return line[loc[1]:], nil
	case v2Color:
		return matchV2Color(s, line, lineNo)
	default:
		return line, matchErr("internal error: unknown v2 segment type")
	}
}

func findPlaceholder(placeholders map[string]v2Placeholder, shortName string) (v2Placeholder, bool) {
	for key, ph := range placeholders {
		if ph.Name == shortName || key == "__"+shortName+"__" {
			return ph, true
		}
	}
	return v2Placeholder{}, false
}

func matchV2Color(c v2Color, line string, lineNo int) (string, error) {
	open, err := resolveColorOpen(c.Spec)
	if err != nil {
		return line, err
	}
	want := open + c.Text + colorReset
	if !strings.HasPrefix(line, want) {
		if strings.HasPrefix(line, c.Text) {
			return line, matchErr("output mismatch at line %d:\n  ansi-color expected styled %q, got plain text", lineNo, c.Text)
		}
		return line, matchErr("output mismatch at line %d:\n  ansi-color expected %q prefix, got %q", lineNo, want, line)
	}
	return line[len(want):], nil
}

func parseV2(headerYAML, body string) (v2Pattern, error) {
	var raw map[string]any
	if err := yaml.Unmarshal([]byte(headerYAML), &raw); err != nil {
		return v2Pattern{}, parseErr(0, "invalid YAML header: %v", err)
	}

	placeholders := make(map[string]v2Placeholder)
	for key, val := range raw {
		if key == "version" {
			continue
		}
		if !placeholderNameRE.MatchString(key) {
			continue
		}
		text, ok := val.(string)
		if !ok {
			return v2Pattern{}, parseErr(0, "invalid placeholder definition for %s", key)
		}
		ph, err := parsePlaceholderDef(key, text)
		if err != nil {
			return v2Pattern{}, err
		}
		placeholders[key] = ph
	}

	lines, trailing := splitTemplateLines(body)
	var items []v2Item
	for i, line := range lines {
		pos := lineOffset(lines, i)
		if omitIntentRE.MatchString(strings.TrimSpace(line)) {
			count, ok := isOmitLine(line)
			if !ok {
				return v2Pattern{}, parseErr(pos, "invalid omit marker syntax")
			}
			items = append(items, v2OmitLine{Count: count})
			continue
		}
		item, err := parseV2Line(line, pos, placeholders, hasRegexIntent(line))
		if err != nil {
			return v2Pattern{}, err
		}
		items = append(items, item)
	}

	if err := validatePlaceholdersUsed(body, placeholders); err != nil {
		return v2Pattern{}, err
	}

	return v2Pattern{
		placeholders:    placeholders,
		items:           items,
		trailingNewline: trailing,
	}, nil
}

func parsePlaceholderDef(name, raw string) (v2Placeholder, error) {
	parts := splitCompactParts(raw)
	if len(parts) == 0 {
		return v2Placeholder{}, parseErr(0, "empty placeholder definition for %s", name)
	}

	meta := make(map[string]string)
	var typ string
	for _, part := range parts {
		eq := strings.Index(part, "=")
		if eq <= 0 {
			break
		}
		key := strings.TrimSpace(part[:eq])
		val := strings.TrimSpace(part[eq+1:])
		if key == "" || val == "" {
			break
		}
		if key == "type" {
			typ = val
		} else {
			meta[key] = val
		}
	}

	if typ == "" {
		return v2Placeholder{}, parseErr(0, "placeholder %s missing type", name)
	}
	if typ != "string" && typ != "number" {
		return v2Placeholder{}, parseErr(0, "unknown placeholder type %q for %s", typ, name)
	}

	shortName := strings.Trim(name, "_")
	return v2Placeholder{Name: shortName, Type: typ, Metadata: meta}, nil
}

func splitCompactParts(raw string) []string {
	var parts []string
	var cur strings.Builder
	depth := 0
	for _, ch := range raw {
		switch ch {
		case '(':
			depth++
			cur.WriteRune(ch)
		case ')':
			if depth > 0 {
				depth--
			}
			cur.WriteRune(ch)
		case ',':
			if depth == 0 {
				parts = append(parts, strings.TrimSpace(cur.String()))
				cur.Reset()
				continue
			}
			cur.WriteRune(ch)
		default:
			cur.WriteRune(ch)
		}
	}
	if s := strings.TrimSpace(cur.String()); s != "" {
		parts = append(parts, s)
	}
	return parts
}

func validatePlaceholdersUsed(body string, defined map[string]v2Placeholder) error {
	used := placeholderNameRE.FindAllString(body, -1)
	seen := make(map[string]bool)
	for _, name := range used {
		if seen[name] {
			continue
		}
		seen[name] = true
		if _, ok := defined[name]; !ok {
			short := strings.Trim(name, "_")
			return parseErr(0, "undefined placeholder __%s__", short)
		}
	}
	return nil
}

func parseV2Line(line string, pos int, placeholders map[string]v2Placeholder, regexIntent bool) (v2Item, error) {
	if regexIntent {
		pattern, err := buildRegexPattern(line, placeholders)
		if err != nil {
			return nil, err
		}
		if _, err := regexp.Compile(pattern); err != nil {
			return nil, parseErr(pos, "invalid regex: %v", err)
		}
		return v2RegexLine{Pattern: pattern}, nil
	}

	if !strings.Contains(line, "__") && !strings.Contains(line, ansiColorOpenPrefix) {
		return v2LiteralLine{Text: line}, nil
	}

	segments, err := parseV2Segments(line, pos, placeholders)
	if err != nil {
		return nil, err
	}
	if len(segments) == 1 {
		if lit, ok := segments[0].(v2Literal); ok {
			return v2LiteralLine{Text: lit.Text}, nil
		}
	}
	return v2PatternLine{Segments: segments}, nil
}

func parseV2Segments(line string, pos int, placeholders map[string]v2Placeholder) ([]v2Segment, error) {
	var segments []v2Segment
	i := 0
	for i < len(line) {
		if strings.HasPrefix(line[i:], ansiColorOpenPrefix) {
			seg, n, err := parseColorSegment(line, i, pos+i)
			if err != nil {
				return nil, err
			}
			segments = append(segments, seg)
			i += n
			continue
		}
		nextPH := placeholderNameRE.FindStringIndex(line[i:])
		nextColor := strings.Index(line[i:], ansiColorOpenPrefix)
		litEnd := len(line)
		if nextPH != nil {
			litEnd = i + nextPH[0]
		}
		if nextColor >= 0 && i+nextColor < litEnd {
			litEnd = i + nextColor
		}
		if litEnd > i {
			segments = append(segments, v2Literal{Text: line[i:litEnd]})
			i = litEnd
			continue
		}
		if nextPH != nil {
			name := line[i+nextPH[0] : i+nextPH[1]]
			if _, ok := placeholders[name]; !ok {
				short := strings.Trim(name, "_")
				return nil, parseErr(pos+i, "undefined placeholder __%s__", short)
			}
			short := strings.Trim(name, "_")
			segments = append(segments, v2PlaceholderRef{Name: short})
			i += nextPH[1]
			continue
		}
		if nextColor >= 0 {
			continue
		}
		break
	}
	return segments, nil
}

func parseColorSegment(line string, start, pos int) (v2Segment, int, error) {
	openEnd := strings.Index(line[start:], ">")
	if openEnd < 0 {
		return nil, 0, parseErr(pos, "unclosed <ansi-color>")
	}
	openEnd += start
	openTag := line[start+1 : openEnd]
	if !strings.HasPrefix(openTag, ansiColorTagName) {
		return nil, 0, parseErr(pos, "expected <ansi-color>")
	}
	specText := strings.TrimSpace(openTag[len(ansiColorTagName):])
	spec, err := parseColorSpec(specText)
	if err != nil {
		return nil, 0, err
	}
	closeIdx := strings.Index(line[openEnd+1:], ansiColorCloseTag)
	if closeIdx < 0 {
		return nil, 0, parseErr(pos, "unclosed <ansi-color>")
	}
	inner := line[openEnd+1 : openEnd+1+closeIdx]
	if inner == "" {
		return nil, 0, parseErr(pos, "empty ansi-color inner text")
	}
	consumed := openEnd + 1 + closeIdx + len(ansiColorCloseTag) - start
	return v2Color{Spec: spec, Text: inner}, consumed, nil
}

func buildRegexPattern(line string, placeholders map[string]v2Placeholder) (string, error) {
	var b strings.Builder
	i := 0
	for i < len(line) {
		if strings.HasPrefix(line[i:], ansiColorOpenPrefix) {
			openEnd := strings.Index(line[i:], ">")
			if openEnd < 0 {
				return "", parseErr(-1, "unclosed <ansi-color>")
			}
			openEnd += i
			openTag := line[i+1 : openEnd]
			specText := strings.TrimSpace(strings.TrimPrefix(openTag, ansiColorTagName))
			spec, err := parseColorSpec(specText)
			if err != nil {
				return "", err
			}
			closeIdx := strings.Index(line[openEnd+1:], ansiColorCloseTag)
			if closeIdx < 0 {
				return "", parseErr(-1, "unclosed <ansi-color>")
			}
			inner := line[openEnd+1 : openEnd+1+closeIdx]
			open, err := resolveColorOpen(spec)
			if err != nil {
				return "", err
			}
			b.WriteString(regexp.QuoteMeta(open))
			b.WriteString(regexp.QuoteMeta(inner))
			b.WriteString(regexp.QuoteMeta(colorReset))
			i = openEnd + 1 + closeIdx + len(ansiColorCloseTag)
			continue
		}
		nextPH := placeholderNameRE.FindStringIndex(line[i:])
		nextColor := strings.Index(line[i:], ansiColorOpenPrefix)
		litEnd := len(line)
		if nextPH != nil {
			litEnd = i + nextPH[0]
		}
		if nextColor >= 0 && i+nextColor < litEnd {
			litEnd = i + nextColor
		}
		if litEnd > i {
			// Regex-intent lines: non-placeholder text is raw RE syntax (e.g. .* or (a|b)).
			// Do not QuoteMeta here — that would turn intentional metacharacters into literals
			// and break pure-regex cookbook cases (V2-M4, V2-M13).
			b.WriteString(line[i:litEnd])
			i = litEnd
			continue
		}
		if nextPH != nil {
			name := line[i+nextPH[0] : i+nextPH[1]]
			ph, ok := placeholders[name]
			if !ok {
				short := strings.Trim(name, "_")
				return "", parseErr(-1, "undefined placeholder __%s__", short)
			}
			sub, err := placeholderSubpattern(ph.Type)
			if err != nil {
				return "", err
			}
			b.WriteString(sub)
			i += nextPH[1]
			continue
		}
		break
	}
	return b.String(), nil
}

func splitTemplateLines(s string) ([]string, bool) {
	trailing := strings.HasSuffix(s, "\n")
	if s == "" {
		return nil, trailing
	}
	body := strings.TrimSuffix(s, "\n")
	if body == "" && trailing {
		return []string{""}, trailing
	}
	return strings.Split(body, "\n"), trailing
}

func lineOffset(lines []string, lineIdx int) int {
	if lineIdx <= 0 {
		return 0
	}
	offset := 0
	for i := 0; i < lineIdx && i < len(lines); i++ {
		offset += len(lines[i]) + 1
	}
	return offset
}

func trimLeadingBlankLinesBeforeV2Header(s string) string {
	for len(s) > 0 {
		if strings.HasPrefix(s, "---") {
			return s
		}
		s = strings.TrimLeft(s, " \t")
		if strings.HasPrefix(s, "---") {
			return s
		}
		if strings.HasPrefix(s, "\r\n") {
			s = s[2:]
			continue
		}
		if strings.HasPrefix(s, "\n") {
			s = s[1:]
			continue
		}
		return s
	}
	return s
}

func detectV2(template string) (bool, string, string, error) {
	template = trimLeadingBlankLinesBeforeV2Header(template)
	if !strings.HasPrefix(template, "---") {
		return false, "", template, nil
	}
	rest := template[3:]
	if strings.HasPrefix(rest, "\r\n") {
		rest = rest[2:]
	} else if strings.HasPrefix(rest, "\n") {
		rest = rest[1:]
	} else {
		return false, "", template, nil
	}
	closeIdx := strings.Index(rest, "\n---")
	if closeIdx < 0 {
		return false, "", template, nil
	}
	headerYAML := rest[:closeIdx]
	body := rest[closeIdx+4:]
	if strings.HasPrefix(body, "\r\n") {
		body = body[2:]
	} else if strings.HasPrefix(body, "\n") {
		body = body[1:]
	}

	var raw map[string]any
	if err := yaml.Unmarshal([]byte(headerYAML), &raw); err != nil {
		return false, "", template, nil
	}
	version, ok := raw["version"]
	if !ok {
		return false, "", template, nil
	}
	switch v := version.(type) {
	case int:
		if v != 2 {
			return false, "", template, nil
		}
	case int64:
		if v != 2 {
			return false, "", template, nil
		}
	case float64:
		if int(v) != 2 {
			return false, "", template, nil
		}
	default:
		if fmt.Sprint(v) != "2" {
			return false, "", template, nil
		}
	}
	return true, headerYAML, body, nil
}

var (
	placeholderNameRE = regexp.MustCompile(`__[A-Z][A-Z0-9_]*__`)
	omitLineRE        = regexp.MustCompile(`^\.\.\.\s*(\d+)\s*lines\s+omitted\s*\.\.\.$`)
	omitIntentRE      = regexp.MustCompile(`^\.\.\.\s*.+\s+lines\s+omitted\s*\.\.\.$`)
)

func isOmitLine(line string) (int, bool) {
	m := omitLineRE.FindStringSubmatch(strings.TrimSpace(line))
	if m == nil {
		return 0, false
	}
	var count int
	for _, ch := range m[1] {
		count = count*10 + int(ch-'0')
	}
	return count, true
}

func hasRegexIntent(line string) bool {
	masked := maskProtectedRegions(line)
	return scanRegexSignals(masked)
}

func maskProtectedRegions(line string) string {
	out := line
	for _, name := range placeholderNameRE.FindAllString(line, -1) {
		out = strings.ReplaceAll(out, name, strings.Repeat(" ", len(name)))
	}
	for {
		start := strings.Index(out, ansiColorOpenPrefix)
		if start < 0 {
			break
		}
		openEnd := strings.Index(out[start:], ">")
		if openEnd < 0 {
			break
		}
		openEnd += start
		closeStart := strings.Index(out[openEnd+1:], ansiColorCloseTag)
		if closeStart < 0 {
			break
		}
		closeStart += openEnd + 1
		span := out[start : closeStart+len(ansiColorCloseTag)]
		out = strings.Replace(out, span, strings.Repeat(" ", len(span)), 1)
	}
	return out
}

func scanRegexSignals(s string) bool {
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '.':
			if i+1 < len(s) {
				switch s[i+1] {
				case '*', '+', '?':
					return true
				case '.':
					return true
				}
			}
		case '^':
			if i == 0 {
				return true
			}
		case '$':
			if i == len(s)-1 {
				return true
			}
		case '\\':
			if i+1 < len(s) {
				switch s[i+1] {
				case 'd', 'D', 'w', 'W', 's', 'S', 'b', 'B':
					return true
				}
			}
		case '[':
			if findBalancedBracket(s, i) {
				return true
			}
		case '|':
			if isAlternationSignal(s, i) {
				return true
			}
		case '{':
			if isQuantifierBrace(s, i) {
				return true
			}
		case '*', '+':
			if i+1 < len(s) && s[i+1] == '?' {
				return true
			}
		}
	}
	return false
}

func findBalancedBracket(s string, start int) bool {
	if start >= len(s) || s[start] != '[' {
		return false
	}
	depth := 0
	for i := start; i < len(s); i++ {
		if s[i] == '[' {
			depth++
		} else if s[i] == ']' {
			depth--
			if depth == 0 {
				return true
			}
		}
	}
	return false
}

func isAlternationSignal(s string, pipeIdx int) bool {
	left := strings.TrimSpace(s[:pipeIdx])
	right := strings.TrimSpace(s[pipeIdx+1:])
	return left != "" && right != ""
}

func isQuantifierBrace(s string, start int) bool {
	if start >= len(s) || s[start] != '{' {
		return false
	}
	end := strings.Index(s[start:], "}")
	if end < 0 {
		return false
	}
	inner := s[start+1 : start+end]
	if inner == "" {
		return false
	}
	for i, ch := range inner {
		if ch == ',' {
			continue
		}
		if ch < '0' || ch > '9' {
			if i == 0 {
				return false
			}
			return false
		}
	}
	return true
}

func placeholderSubpattern(typ string) (string, error) {
	switch typ {
	case "string":
		return `[^\n]*?`, nil
	case "number":
		return `-?\d+(?:\.\d+)?`, nil
	default:
		return "", parseErr(-1, "unknown placeholder type %q", typ)
	}
}

func summaryV2(p v2Pattern) string {
	var parts []string
	if len(p.placeholders) > 0 {
		parts = append(parts, summarizeV2Placeholders(p.placeholders))
	}
	for _, item := range p.items {
		parts = append(parts, summarizeV2Item(item))
	}
	return combineV2SummaryParts(parts)
}

func summarizeV2Placeholders(placeholders map[string]v2Placeholder) string {
	names := make([]string, 0, len(placeholders))
	for _, ph := range placeholders {
		names = append(names, ph.Name)
	}
	sort.Strings(names)
	var defs []string
	for _, name := range names {
		for _, ph := range placeholders {
			if ph.Name == name {
				defs = append(defs, summarizeV2Placeholder(ph))
				break
			}
		}
	}
	return "Placeholders:" + strings.Join(defs, ",")
}

func summarizeV2Placeholder(ph v2Placeholder) string {
	s := fmt.Sprintf("%s{%s", ph.Name, ph.Type)
	keys := make([]string, 0, len(ph.Metadata))
	for k := range ph.Metadata {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		s += "," + k + "=" + ph.Metadata[k]
	}
	s += "}"
	return s
}

func summarizeV2Item(item v2Item) string {
	switch it := item.(type) {
	case v2LiteralLine:
		return "LiteralLine"
	case v2PatternLine:
		return "PatternLine segments:" + summarizeV2Segments(it.Segments)
	case v2RegexLine:
		return "RegexLine"
	case v2OmitLine:
		return fmt.Sprintf("OmitLine{%d}", it.Count)
	default:
		return "Unknown"
	}
}

func summarizeV2Segments(segs []v2Segment) string {
	parts := make([]string, 0, len(segs))
	for _, seg := range segs {
		parts = append(parts, summarizeV2Segment(seg))
	}
	return strings.Join(parts, "+")
}

func summarizeV2Segment(seg v2Segment) string {
	switch s := seg.(type) {
	case v2Literal:
		return "Literal"
	case v2PlaceholderRef:
		return fmt.Sprintf("Placeholder{%s}", s.Name)
	case v2Color:
		return "Color " + strings.Join(s.Spec.Tokens, " ")
	default:
		return "Unknown"
	}
}

func combineV2SummaryParts(parts []string) string {
	if len(parts) == 0 {
		return ""
	}
	itemParts := parts
	if strings.HasPrefix(parts[0], "Placeholders:") {
		if len(parts) == 1 {
			return parts[0]
		}
		itemParts = parts[1:]
	}
	if len(itemParts) >= 2 && itemParts[0] == "LiteralLine" {
		allLiteral := true
		for _, p := range itemParts {
			if p != "LiteralLine" {
				allLiteral = false
				break
			}
		}
		if allLiteral {
			prefix := ""
			if strings.HasPrefix(parts[0], "Placeholders:") {
				prefix = parts[0] + "+"
			}
			return prefix + fmt.Sprintf("LiteralLine×%d", len(itemParts))
		}
	}
	if strings.HasPrefix(parts[0], "Placeholders:") {
		return strings.Join(parts, "+")
	}
	return strings.Join(itemParts, "+")
}
