// Code generated by script/generate/embed-assert; DO NOT EDIT.

//go:build ignore

package assert

import (
	"fmt"
	"regexp"
	"strings"
	"testing"
	"unicode"
)

var namedAnsiColors = map[string]string{
	"bold":  "1",
	"red":   "31",
	"green": "32",
	"gray":  "90",
}

func resolveAnsiOpen(spec AnsiColorSpec) (string, error) {
	var b strings.Builder
	for _, tok := range spec.Tokens {
		params, err := ansiTokenParams(tok)
		if err != nil {
			return "", err
		}
		b.WriteString("\x1b[")
		b.WriteString(params)
		b.WriteString("m")
	}
	return b.String(), nil
}

func ansiTokenParams(tok string) (string, error) {
	if strings.HasPrefix(tok, "#") {
		return tok[1:], nil
	}
	params, ok := namedAnsiColors[tok]
	if !ok {
		return "", parseErr(-1, "unknown ansi color name %q; use # for raw SGR", tok)
	}
	return params, nil
}

func parseAnsiSpec(specText string) (AnsiColorSpec, error) {
	specText = strings.TrimSpace(specText)
	if specText == "" {
		return AnsiColorSpec{}, parseErr(-1, "empty ansi-color specifier")
	}
	var tokens []string
	for specText != "" {
		specText = strings.TrimLeft(specText, " \t")
		if specText == "" {
			break
		}
		if specText[0] == '#' {
			end := 1
			for end < len(specText) && specText[end] != ' ' && specText[end] != '\t' {
				end++
			}
			tokens = append(tokens, specText[:end])
			specText = specText[end:]
			continue
		}
		end := 0
		for end < len(specText) && specText[end] != ' ' && specText[end] != '\t' {
			end++
		}
		name := specText[:end]
		if _, ok := namedAnsiColors[name]; !ok {
			return AnsiColorSpec{}, parseErr(-1, "unknown ansi color name %q", name)
		}
		tokens = append(tokens, name)
		specText = specText[end:]
	}
	return AnsiColorSpec{Tokens: tokens}, nil
}

const ansiReset = "\x1b[0m"

type Pattern struct {
	items           []Item
	trailingNewline bool
}

type Item interface {
	isItem()
}

type LiteralLine struct {
	Text string
}

func (LiteralLine) isItem() {}

type PatternLine struct {
	Segments []Segment
}

func (PatternLine) isItem() {}

type Segment interface {
	isSegment()
}

type Literal struct {
	Text string
}

func (Literal) isSegment() {}

type Hint struct {
	Label string
	Text  string
}

func (Hint) isSegment() {}

type AnsiColor struct {
	Spec AnsiColorSpec
	Text string
}

func (AnsiColor) isSegment() {}

type AnsiColorSpec struct {
	Tokens []string
}

type InlineOptional struct {
	Text string
}

func (InlineOptional) isSegment() {}

type InlineAnyOf struct {
	Branches []InlineExpectBranch
}

func (InlineAnyOf) isSegment() {}

type InlineExpectBranch struct {
	Segments []Segment
}

type InlineRegex struct {
	Pattern string
}

func (InlineRegex) isSegment() {}

type RegexLine struct {
	Pattern string
}

func (RegexLine) isItem() {}

type BlockOptional struct {
	Items []Item
}

func (BlockOptional) isItem() {}

type AnyOfBlock struct {
	Branches []ExpectBranch
}

func (AnyOfBlock) isItem() {}

type ExpectBranch struct {
	Items []Item
}

type ContainsBlock struct {
	Fragments []ContainsFragment
}

func (ContainsBlock) isItem() {}

type ContainsMatchMode int

const (
	ContainsFullLine ContainsMatchMode = iota
	ContainsStartWith
	ContainsEndWith
)

type ContainsFragment struct {
	Mode     ContainsMatchMode
	Text     string
	Segments []Segment
}

type parseError struct {
	pos int
	msg string
}

func (e *parseError) Error() string {
	if e.pos >= 0 {
		return fmt.Sprintf("parse error at position %d: %s", e.pos, e.msg)
	}
	return fmt.Sprintf("parse error: %s", e.msg)
}

func parseErr(pos int, format string, args ...any) error {
	return &parseError{pos: pos, msg: fmt.Sprintf(format, args...)}
}

type matchError struct {
	msg string
}

func (e *matchError) Error() string {
	return e.msg
}

func matchErr(format string, args ...any) error {
	return &matchError{msg: fmt.Sprintf(format, args...)}
}

// Match compares actual output against pattern. nil means success.
func Match(p Pattern, actual string, opts ...Option) error {
	cfg := applyOptions(opts...)
	if cfg.normalizeNewlines {
		actual = strings.ReplaceAll(actual, "\r\n", "\n")
	}

	if cfg.mode == matchContains {
		return matchContainsMode(p, actual)
	}
	return matchExactMode(p, actual)
}

func matchContainsMode(p Pattern, actual string) error {
	for i := 0; i <= len(actual); i++ {
		if i == 0 || (i > 0 && actual[i-1] == '\n') {
			sub := actual[i:]
			if err := matchPrefixAt(p, sub, 0, false); err == nil {
				return nil
			}
		}
	}
	return matchErr("output does not contain expected contiguous subregion")
}

func matchExactMode(p Pattern, actual string) error {
	allowGaps := patternHasContains(p.items)
	if err := checkTrailingNewline(p.trailingNewline, actual); err != nil {
		return err
	}
	return matchExactAt(p, actual, 0, allowGaps, true)
}

func matchPrefixAt(p Pattern, actual string, lineBase int, allowGaps bool) error {
	return matchExactAt(p, actual, lineBase, allowGaps, false)
}

func checkTrailingNewline(templateTrailing bool, actual string) error {
	actualTrailing := len(actual) > 0 && actual[len(actual)-1] == '\n'
	if templateTrailing != actualTrailing {
		return matchErr("output mismatch: trailing newline policy violated")
	}
	return nil
}

func matchExactAt(p Pattern, actual string, lineBase int, allowGaps bool, requireEOF bool) error {
	lines := splitActualLines(actual)
	st := &matchState{
		lines:     lines,
		lineBase:  lineBase,
		allowGaps: allowGaps,
	}

	for _, frag := range collectContainsFragments(p.items) {
		if err := st.checkContainsFragment(frag); err != nil {
			return err
		}
	}

	cursor := 0
	for _, item := range p.items {
		switch it := item.(type) {
		case ContainsBlock:
			continue
		default:
			n, err := st.matchItem(it, cursor)
			if err != nil {
				return err
			}
			cursor = n
		}
	}

	if requireEOF && !allowGaps && cursor < len(lines) {
		return matchErr("unexpected extra output at line %d", lineBase+cursor+1)
	}
	return nil
}

type matchState struct {
	lines     []string
	lineBase  int
	allowGaps bool
}

func splitActualLines(actual string) []string {
	if actual == "" {
		return nil
	}
	body := strings.TrimSuffix(actual, "\n")
	if body == "" {
		return nil
	}
	return strings.Split(body, "\n")
}

func patternHasContains(items []Item) bool {
	for _, item := range items {
		switch it := item.(type) {
		case ContainsBlock:
			return true
		case BlockOptional:
			if patternHasContains(it.Items) {
				return true
			}
		case AnyOfBlock:
			for _, b := range it.Branches {
				if patternHasContains(b.Items) {
					return true
				}
			}
		}
	}
	return false
}

func collectContainsFragments(items []Item) []ContainsFragment {
	var out []ContainsFragment
	for _, item := range items {
		switch it := item.(type) {
		case ContainsBlock:
			out = append(out, it.Fragments...)
		case BlockOptional:
			out = append(out, collectContainsFragments(it.Items)...)
		case AnyOfBlock:
			for _, b := range it.Branches {
				out = append(out, collectContainsFragments(b.Items)...)
			}
		}
	}
	return out
}

func (st *matchState) checkContainsFragment(frag ContainsFragment) error {
	for _, line := range st.lines {
		switch frag.Mode {
		case ContainsFullLine:
			if len(frag.Segments) > 0 {
				if _, err := st.matchSegments(frag.Segments, line, st.lineBase+1); err == nil {
					return nil
				}
				continue
			}
			if line == frag.Text || strings.HasPrefix(line, frag.Text) {
				return nil
			}
		case ContainsStartWith:
			if strings.HasPrefix(line, frag.Text) || strings.Contains(line, frag.Text) {
				return nil
			}
		case ContainsEndWith:
			if strings.HasSuffix(line, frag.Text) {
				return nil
			}
		}
	}
	if len(frag.Segments) > 0 {
		return matchErr("missing contains pattern fragment")
	}
	return matchErr("missing contains fragment %q", frag.Text)
}

func (st *matchState) matchItem(item Item, cursor int) (int, error) {
	switch it := item.(type) {
	case LiteralLine:
		return st.matchLiteralLine(it.Text, cursor)
	case PatternLine:
		return st.matchPatternLine(it, cursor)
	case RegexLine:
		return st.matchRegexLine(it.Pattern, cursor)
	case BlockOptional:
		return st.matchBlockOptional(it, cursor)
	case AnyOfBlock:
		return st.matchAnyOfBlock(it, cursor)
	default:
		return cursor, matchErr("internal error: unknown item type")
	}
}

func (st *matchState) matchLiteralLine(want string, cursor int) (int, error) {
	if st.allowGaps {
		for i := cursor; i < len(st.lines); i++ {
			if st.lines[i] == want {
				return i + 1, nil
			}
		}
		return cursor, matchErr("output mismatch at line %d:\n  want: %q\n  got:  (not found)", st.lineBase+cursor+1, want)
	}
	if cursor >= len(st.lines) {
		return cursor, matchErr("output mismatch at line %d:\n  want: %q\n  got:  (end of output)", st.lineBase+cursor+1, want)
	}
	got := st.lines[cursor]
	if got != want {
		return cursor, matchErr("output mismatch at line %d:\n  want: %q\n  got:  %q", st.lineBase+cursor+1, want, got)
	}
	return cursor + 1, nil
}

func (st *matchState) matchPatternLine(pl PatternLine, cursor int) (int, error) {
	if cursor >= len(st.lines) {
		return cursor, matchErr("output mismatch at line %d: unexpected end of output", st.lineBase+cursor+1)
	}
	line := st.lines[cursor]
	rest, err := st.matchSegments(pl.Segments, line, st.lineBase+cursor+1)
	if err != nil {
		return cursor, err
	}
	if rest != "" {
		return cursor, matchErr("output mismatch at line %d:\n  unparsed remainder: %q", st.lineBase+cursor+1, rest)
	}
	return cursor + 1, nil
}

func (st *matchState) matchRegexLine(pattern string, cursor int) (int, error) {
	if cursor >= len(st.lines) {
		return cursor, matchErr("output mismatch at line %d: regex expected a line", st.lineBase+cursor+1)
	}
	re := regexp.MustCompile(pattern)
	if !re.MatchString(st.lines[cursor]) {
		return cursor, matchErr("output mismatch at line %d:\n  regex %q did not match %q", st.lineBase+cursor+1, pattern, st.lines[cursor])
	}
	return cursor + 1, nil
}

func (st *matchState) matchBlockOptional(bo BlockOptional, cursor int) (int, error) {
	if len(bo.Items) == 0 {
		return cursor, nil
	}
	end, err := st.matchItems(bo.Items, cursor, false)
	if err == nil {
		return end, nil
	}
	return cursor, nil
}

func (st *matchState) matchItems(items []Item, cursor int, required bool) (int, error) {
	pos := cursor
	for _, item := range items {
		n, err := st.matchItem(item, pos)
		if err != nil {
			if required {
				return pos, err
			}
			return cursor, err
		}
		pos = n
	}
	return pos, nil
}

func (st *matchState) matchAnyOfBlock(ao AnyOfBlock, cursor int) (int, error) {
	var reports []string
	for i, branch := range ao.Branches {
		end, err := st.matchItems(branch.Items, cursor, true)
		if err == nil {
			return end, nil
		}
		reports = append(reports, fmt.Sprintf("  branch %d (<expect>):\n    %s", i+1, indentMatchErr(err)))
	}
	msg := fmt.Sprintf("output mismatch at line %d: <any-of> — no branch matched\n  actual: %q\n%s",
		st.lineBase+cursor+1, st.lineAt(cursor), strings.Join(reports, "\n"))
	return cursor, &matchError{msg: msg}
}

func (st *matchState) lineAt(cursor int) string {
	if cursor >= len(st.lines) {
		return ""
	}
	return st.lines[cursor]
}

func indentMatchErr(err error) string {
	s := err.Error()
	s = strings.ReplaceAll(s, "\n", "\n    ")
	return s
}

func (st *matchState) matchSegments(segs []Segment, line string, lineNo int) (string, error) {
	rest := line
	for _, seg := range segs {
		var err error
		rest, err = st.matchSegment(seg, rest, lineNo)
		if err != nil {
			return rest, err
		}
	}
	return rest, nil
}

func (st *matchState) matchSegment(seg Segment, line string, lineNo int) (string, error) {
	switch s := seg.(type) {
	case Literal:
		if !strings.HasPrefix(line, s.Text) {
			return line, matchErr("output mismatch at line %d:\n  want prefix: %q\n  got:         %q", lineNo, s.Text, line)
		}
		return line[len(s.Text):], nil
	case Hint:
		if !strings.HasPrefix(line, s.Text) {
			return line, matchErr("output mismatch at line %d:\n  hint:%s expected %q, got %q", lineNo, s.Label, s.Text, line)
		}
		return line[len(s.Text):], nil
	case InlineOptional:
		if strings.HasPrefix(line, s.Text) {
			return line[len(s.Text):], nil
		}
		return line, nil
	case InlineAnyOf:
		return st.matchInlineAnyOf(s, line, lineNo)
	case AnsiColor:
		return st.matchAnsiColor(s, line, lineNo)
	case InlineRegex:
		return st.matchInlineRegex(s, line, lineNo)
	default:
		return line, matchErr("internal error: unknown segment type")
	}
}

func (st *matchState) matchInlineAnyOf(iao InlineAnyOf, line string, lineNo int) (string, error) {
	var reports []string
	for i, branch := range iao.Branches {
		rest, err := st.matchSegments(branch.Segments, line, lineNo)
		if err == nil && rest != "" {
			// branch matched prefix but left remainder — only valid if remainder consumed later
		}
		if err == nil {
			return rest, nil
		}
		reports = append(reports, fmt.Sprintf("  branch %d: %s", i+1, err.Error()))
	}
	return line, matchErr("output mismatch at line %d: inline <any-of> — no branch matched\n%s", lineNo, strings.Join(reports, "\n"))
}

func (st *matchState) matchInlineRegex(ir InlineRegex, line string, lineNo int) (string, error) {
	re := regexp.MustCompile(ir.Pattern)
	loc := re.FindStringIndex(line)
	if loc == nil || loc[0] != 0 {
		return line, matchErr("output mismatch at line %d:\n  regex %q did not match prefix of %q", lineNo, ir.Pattern, line)
	}
	return line[loc[1]:], nil
}

func (st *matchState) matchAnsiColor(ac AnsiColor, line string, lineNo int) (string, error) {
	open, err := resolveAnsiOpen(ac.Spec)
	if err != nil {
		return line, err
	}
	want := open + ac.Text + ansiReset
	if !strings.HasPrefix(line, want) {
		if strings.HasPrefix(line, ac.Text) {
			return line, matchErr("output mismatch at line %d:\n  ansi-color expected styled %q, got plain text", lineNo, ac.Text)
		}
		return line, matchErr("output mismatch at line %d:\n  ansi-color expected %q prefix, got %q", lineNo, want, line)
	}
	return line[len(want):], nil
}

type Option interface {
	apply(*matchConfig)
}

type matchConfig struct {
	mode              matchMode
	normalizeNewlines bool
}

type matchMode int

const (
	matchExact matchMode = iota
	matchContains
)

type containsOption struct{}

func (containsOption) apply(cfg *matchConfig) {
	cfg.mode = matchContains
}

// Contains enables MatchContains mode: the template must appear as a contiguous
// ordered subregion of actual output.
func Contains() Option {
	return containsOption{}
}

type normalizeNewlinesOption struct {
	v bool
}

func (o normalizeNewlinesOption) apply(cfg *matchConfig) {
	cfg.normalizeNewlines = o.v
}

// NormalizeNewlines controls \r\n → \n normalization (default true).
func NormalizeNewlines(v bool) Option {
	return normalizeNewlinesOption{v: v}
}

func defaultMatchConfig() matchConfig {
	return matchConfig{
		mode:              matchExact,
		normalizeNewlines: true,
	}
}

func applyOptions(opts ...Option) matchConfig {
	cfg := defaultMatchConfig()
	for _, o := range opts {
		o.apply(&cfg)
	}
	return cfg
}

// Output parses template, matches actual output, and calls t.Fatal on failure.
func Output(t *testing.T, actual, template string, opts ...Option) {
	t.Helper()
	p, err := Parse(template)
	if err != nil {
		t.Fatalf("parse output template: %v", err)
	}
	if err := Match(p, actual, opts...); err != nil {
		t.Fatal(err)
	}
}

// Parse parses template text into a Pattern.
func Parse(template string) (Pattern, error) {
	p := &parser{src: template}
	lines, trailing := splitTemplateLines(p.src)
	p.lines = lines
	p.idx = 0
	items, err := p.parseItems()
	if err != nil {
		return Pattern{}, err
	}
	return Pattern{items: items, trailingNewline: trailing}, nil
}

// MustParse parses template text or panics.
func MustParse(template string) Pattern {
	p, err := Parse(template)
	if err != nil {
		panic(err)
	}
	return p
}

type parser struct {
	src   string
	lines []string
	idx   int
}

func (p *parser) parseItems() ([]Item, error) {
	var items []Item
	for p.idx < len(p.lines) {
		item, err := p.parseItem()
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, nil
}

func splitTemplateLines(s string) ([]string, bool) {
	trailing := strings.HasSuffix(s, "\n")
	if s == "" {
		return nil, trailing
	}
	body := strings.TrimSuffix(s, "\n")
	if body == "" {
		return nil, trailing
	}
	return strings.Split(body, "\n"), trailing
}

func (p *parser) lineOffset(lineIdx int) int {
	if lineIdx <= 0 {
		return 0
	}
	offset := 0
	for i := 0; i < lineIdx && i < len(p.lines); i++ {
		offset += len(p.lines[i]) + 1
	}
	return offset
}

func (p *parser) parseItem() (Item, error) {
	line := p.lines[p.idx]
	trimmed := strings.TrimSpace(line)

	switch trimmed {
	case "<optional>":
		return p.parseBlockOptional()
	case "<any-of>":
		return p.parseAnyOfBlock()
	case "<contains>":
		return p.parseContainsBlock()
	case "<regex>":
		return p.parseBlockRegex()
	}

	pl, err := p.parseLine(line, p.lineOffset(p.idx))
	if err != nil {
		return nil, err
	}
	p.idx++
	return pl, nil
}

func (p *parser) parseBlockOptional() (Item, error) {
	p.idx++ // skip <optional>
	var inner []Item
	for p.idx < len(p.lines) {
		if strings.TrimSpace(p.lines[p.idx]) == "</optional>" {
			p.idx++
			return BlockOptional{Items: inner}, nil
		}
		item, err := p.parseItem()
		if err != nil {
			return nil, err
		}
		inner = append(inner, item)
	}
	return nil, parseErr(p.lineOffset(p.idx), "unclosed <optional>")
}

func (p *parser) parseAnyOfBlock() (Item, error) {
	p.idx++ // skip <any-of>
	var branches []ExpectBranch
	for p.idx < len(p.lines) {
		if strings.TrimSpace(p.lines[p.idx]) == "</any-of>" {
			p.idx++
			if len(branches) == 0 {
				return nil, parseErr(p.lineOffset(p.idx), "any-of requires at least one branch")
			}
			return AnyOfBlock{Branches: branches}, nil
		}
		if strings.TrimSpace(p.lines[p.idx]) != "<expect>" {
			return nil, parseErr(p.lineOffset(p.idx), "expected <expect> inside <any-of>")
		}
		p.idx++
		var body []Item
		for p.idx < len(p.lines) {
			if strings.TrimSpace(p.lines[p.idx]) == "</expect>" {
				p.idx++
				branches = append(branches, ExpectBranch{Items: body})
				break
			}
			item, err := p.parseItem()
			if err != nil {
				return nil, err
			}
			body = append(body, item)
		}
	}
	return nil, parseErr(p.lineOffset(p.idx), "unclosed <any-of>")
}

func (p *parser) parseContainsBlock() (Item, error) {
	p.idx++ // skip <contains>
	var fragments []ContainsFragment
	for p.idx < len(p.lines) {
		line := p.lines[p.idx]
		trimmed := strings.TrimSpace(line)
		if trimmed == "</contains>" {
			p.idx++
			return ContainsBlock{Fragments: fragments}, nil
		}
		if trimmed == "<start-with>" {
			frag, err := p.parseBlockStartWith()
			if err != nil {
				return nil, err
			}
			fragments = append(fragments, frag)
			continue
		}
		if trimmed == "<end-with>" {
			frag, err := p.parseBlockEndWith()
			if err != nil {
				return nil, err
			}
			fragments = append(fragments, frag)
			continue
		}
		if strings.Contains(line, "<start-with>") {
			frag, consumed, err := p.parseInlineStartWith(line, p.lineOffset(p.idx))
			if err != nil {
				return nil, err
			}
			if !consumed {
				return nil, parseErr(p.lineOffset(p.idx), "invalid start-with fragment")
			}
			fragments = append(fragments, frag)
			p.idx++
			continue
		}
		if strings.Contains(line, "<end-with>") {
			frag, consumed, err := p.parseInlineEndWith(line, p.lineOffset(p.idx))
			if err != nil {
				return nil, err
			}
			if !consumed {
				return nil, parseErr(p.lineOffset(p.idx), "invalid end-with fragment")
			}
			fragments = append(fragments, frag)
			p.idx++
			continue
		}
		parsed, err := p.parseLine(line, p.lineOffset(p.idx))
		if err != nil {
			return nil, err
		}
		switch it := parsed.(type) {
		case LiteralLine:
			fragments = append(fragments, ContainsFragment{Mode: ContainsFullLine, Text: it.Text})
		case PatternLine:
			fragments = append(fragments, ContainsFragment{Mode: ContainsFullLine, Segments: it.Segments})
		default:
			return nil, parseErr(p.lineOffset(p.idx), "unsupported contains fragment")
		}
		p.idx++
	}
	return nil, parseErr(p.lineOffset(p.idx), "unclosed <contains>")
}

func (p *parser) parseBlockStartWith() (ContainsFragment, error) {
	p.idx++
	var textLines []string
	for p.idx < len(p.lines) {
		if strings.TrimSpace(p.lines[p.idx]) == "</start-with>" {
			p.idx++
			return ContainsFragment{Mode: ContainsStartWith, Text: strings.Join(textLines, "\n")}, nil
		}
		textLines = append(textLines, p.lines[p.idx])
		p.idx++
	}
	return ContainsFragment{}, parseErr(p.lineOffset(p.idx), "unclosed <start-with>")
}

func (p *parser) parseBlockEndWith() (ContainsFragment, error) {
	p.idx++
	var textLines []string
	for p.idx < len(p.lines) {
		if strings.TrimSpace(p.lines[p.idx]) == "</end-with>" {
			p.idx++
			return ContainsFragment{Mode: ContainsEndWith, Text: strings.Join(textLines, "\n")}, nil
		}
		textLines = append(textLines, p.lines[p.idx])
		p.idx++
	}
	return ContainsFragment{}, parseErr(p.lineOffset(p.idx), "unclosed <end-with>")
}

func (p *parser) parseInlineStartWith(line string, pos int) (ContainsFragment, bool, error) {
	text, rest, ok, err := parseInlineWrapper(line, "start-with", pos)
	if err != nil || !ok {
		return ContainsFragment{}, false, err
	}
	if strings.TrimSpace(rest) != "" {
		return ContainsFragment{}, false, parseErr(pos, "start-with must be alone on line in block form or consume entire line inline")
	}
	return ContainsFragment{Mode: ContainsStartWith, Text: text}, true, nil
}

func (p *parser) parseInlineEndWith(line string, pos int) (ContainsFragment, bool, error) {
	text, rest, ok, err := parseInlineWrapper(line, "end-with", pos)
	if err != nil || !ok {
		return ContainsFragment{}, false, err
	}
	if strings.TrimSpace(rest) != "" {
		return ContainsFragment{}, false, parseErr(pos, "end-with must be alone on line in block form or consume entire line inline")
	}
	return ContainsFragment{Mode: ContainsEndWith, Text: text}, true, nil
}

func (p *parser) parseBlockRegex() (Item, error) {
	p.idx++ // skip <regex>
	if p.idx >= len(p.lines) {
		return nil, parseErr(p.lineOffset(p.idx), "regex block requires pattern line")
	}
	pattern := p.lines[p.idx]
	if _, err := regexp.Compile(pattern); err != nil {
		return nil, parseErr(p.lineOffset(p.idx), "invalid regex: %v", err)
	}
	p.idx++
	if p.idx >= len(p.lines) || strings.TrimSpace(p.lines[p.idx]) != "</regex>" {
		return nil, parseErr(p.lineOffset(p.idx), "unclosed <regex>")
	}
	p.idx++
	return RegexLine{Pattern: pattern}, nil
}

func (p *parser) parseLine(line string, pos int) (Item, error) {
	if !strings.Contains(line, "<") && !strings.Contains(line, "\\<") {
		return LiteralLine{Text: line}, nil
	}
	segments, err := parseSegments(line, pos)
	if err != nil {
		return nil, err
	}
	if len(segments) == 1 {
		if lit, ok := segments[0].(Literal); ok {
			if strings.Contains(line, "\\<") || strings.Contains(lit.Text, "<") {
				return PatternLine{Segments: segments}, nil
			}
			return LiteralLine{Text: lit.Text}, nil
		}
	}
	return PatternLine{Segments: segments}, nil
}

func parseSegments(line string, pos int) ([]Segment, error) {
	var segments []Segment
	i := 0
	for i < len(line) {
		if line[i] != '<' {
			litStart := i
			for i < len(line) {
				if line[i] == '\\' && i+1 < len(line) && line[i+1] == '<' {
					i += 2
					continue
				}
				if line[i] == '<' {
					break
				}
				i++
			}
			text := strings.ReplaceAll(line[litStart:i], "\\<", "<")
			segments = append(segments, Literal{Text: text})
			continue
		}
		if i > 0 && line[i-1] == '\\' {
			return nil, parseErr(pos+i, "invalid escape")
		}
		seg, n, err := parseTagAt(line, i, pos+i)
		if err != nil {
			return nil, err
		}
		segments = append(segments, seg)
		i += n
	}
	return segments, nil
}

func parseTagAt(line string, start, pos int) (Segment, int, error) {
	if !strings.HasPrefix(line[start:], "<") {
		return nil, 0, parseErr(pos, "expected tag")
	}
	closeIdx := strings.Index(line[start:], ">")
	if closeIdx < 0 {
		return nil, 0, parseErr(pos, "unclosed tag")
	}
	openTag := line[start+1 : start+closeIdx]

	switch {
	case openTag == "optional":
		return parseInlineClose(line, start, "optional", pos, func(inner string) (Segment, error) {
			return InlineOptional{Text: inner}, nil
		})
	case openTag == "any-of":
		return parseInlineAnyOf(line, start, pos)
	case strings.HasPrefix(openTag, "hint:"):
		label := openTag[5:]
		if !isValidLabel(label) {
			return nil, 0, parseErr(pos, "invalid hint label %q", label)
		}
		return parseHintSegment(line, start, label, pos)
	case strings.HasPrefix(openTag, "ansi-color"):
		specText := strings.TrimSpace(openTag[len("ansi-color"):])
		spec, err := parseAnsiSpec(specText)
		if err != nil {
			return nil, 0, err
		}
		return parseInlineClose(line, start, "ansi-color", pos, func(inner string) (Segment, error) {
			if inner == "" {
				return nil, parseErr(pos, "empty ansi-color inner text")
			}
			return AnsiColor{Spec: spec, Text: inner}, nil
		})
	case openTag == "regex":
		return parseInlineClose(line, start, "regex", pos, func(inner string) (Segment, error) {
			if inner == "" {
				return nil, parseErr(pos, "empty regex pattern")
			}
			if _, err := regexp.Compile(inner); err != nil {
				return nil, parseErr(pos, "invalid regex: %v", err)
			}
			return InlineRegex{Pattern: inner}, nil
		})
	default:
		if isRegisteredBareTag(openTag) {
			return nil, 0, parseErr(pos, "unknown or misplaced tag <%s>", openTag)
		}
		return nil, 0, parseErr(pos, "unknown tag <%s>", openTag)
	}
}

func parseInlineAnyOf(line string, start, pos int) (Segment, int, error) {
	openLen := len("<any-of>")
	rest := line[start+openLen:]
	var branches []InlineExpectBranch
	for {
		rest = strings.TrimLeft(rest, " \t")
		if !strings.HasPrefix(rest, "<expect>") {
			return nil, 0, parseErr(pos, "inline any-of requires <expect> branches")
		}
		rest = rest[len("<expect>"):]
		closeIdx := strings.Index(rest, "</expect>")
		if closeIdx < 0 {
			return nil, 0, parseErr(pos, "unclosed <expect>")
		}
		inner := rest[:closeIdx]
		seg, err := parseSegments(inner, pos)
		if err != nil {
			return nil, 0, err
		}
		branches = append(branches, InlineExpectBranch{Segments: seg})
		rest = rest[closeIdx+len("</expect>"):]
		rest = strings.TrimLeft(rest, " \t")
		if strings.HasPrefix(rest, "</any-of>") {
			rest = rest[len("</any-of>"):]
			consumed := len(line) - len(rest) - start
			return InlineAnyOf{Branches: branches}, consumed, nil
		}
	}
}

func parseHintSegment(line string, start int, label string, pos int) (Segment, int, error) {
	openEnd := strings.Index(line[start:], ">")
	if openEnd < 0 {
		return nil, 0, parseErr(pos, "unclosed tag")
	}
	openEnd += start
	rest := line[openEnd+1:]
	closePrefix := "</hint:"
	closeIdx := strings.Index(rest, closePrefix)
	if closeIdx < 0 {
		return nil, 0, parseErr(pos, "unclosed <hint:%s>", label)
	}
	closeRest := rest[closeIdx+len(closePrefix):]
	closeEnd := strings.Index(closeRest, ">")
	if closeEnd < 0 {
		return nil, 0, parseErr(pos, "unclosed <hint:%s>", label)
	}
	closeLabel := closeRest[:closeEnd]
	if closeLabel != label {
		return nil, 0, parseErr(pos, "hint label mismatch: open label %q, close label %q", label, closeLabel)
	}
	inner := rest[:closeIdx]
	if inner == "" {
		return nil, 0, parseErr(pos, "empty hint text")
	}
	consumed := openEnd + 1 + closeIdx + len(closePrefix) + closeEnd + 1 - start
	return Hint{Label: label, Text: inner}, consumed, nil
}

func parseInlineClose(line string, start int, closeName string, pos int, mk func(string) (Segment, error)) (Segment, int, error) {
	openEnd := strings.Index(line[start:], ">")
	if openEnd < 0 {
		return nil, 0, parseErr(pos, "unclosed tag")
	}
	openEnd += start
	closeTag := "</" + closeName + ">"
	closeIdx := strings.Index(line[openEnd+1:], closeTag)
	if closeIdx < 0 {
		return nil, 0, parseErr(pos, "unclosed <%s>", closeName)
	}
	inner := line[openEnd+1 : openEnd+1+closeIdx]
	seg, err := mk(inner)
	if err != nil {
		return nil, 0, err
	}
	consumed := openEnd + 1 + closeIdx + len(closeTag) - start
	return seg, consumed, nil
}

func parseInlineWrapper(line, name string, pos int) (text string, rest string, ok bool, err error) {
	open := "<" + name + ">"
	close := "</" + name + ">"
	start := strings.Index(line, open)
	if start < 0 {
		return "", line, false, nil
	}
	end := strings.Index(line, close)
	if end < 0 {
		return "", "", false, parseErr(pos+start, "unclosed <%s>", name)
	}
	text = line[start+len(open) : end]
	rest = line[:start] + line[end+len(close):]
	return text, rest, true, nil
}

func isValidLabel(label string) bool {
	if label == "" {
		return false
	}
	for i, r := range label {
		if i == 0 {
			if !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return false
		}
	}
	return true
}

func isRegisteredBareTag(name string) bool {
	switch name {
	case "id", "path", "cached", "run", "pass", "cwd", "optional", "any-of", "expect", "contains", "regex", "start-with", "end-with", "ansi-color":
		return true
	default:
		if strings.HasPrefix(name, "hint:") {
			return true
		}
		return false
	}
}

// PatternSummary returns a stable summary string for test introspection.
func PatternSummary(p Pattern) string {
	parts := make([]string, 0, len(p.items))
	for _, item := range p.items {
		parts = append(parts, summarizeItem(item))
	}
	return combineSummaryParts(parts)
}

func combineSummaryParts(parts []string) string {
	if len(parts) == 0 {
		return ""
	}
	if len(parts) >= 2 && parts[0] == "LiteralLine" {
		allLiteral := true
		for _, p := range parts {
			if p != "LiteralLine" {
				allLiteral = false
				break
			}
		}
		if allLiteral {
			return fmt.Sprintf("LiteralLine×%d", len(parts))
		}
	}
	return strings.Join(parts, "+")
}

func summarizeItem(item Item) string {
	switch it := item.(type) {
	case LiteralLine:
		return "LiteralLine"
	case PatternLine:
		return "PatternLine segments:" + summarizeSegments(it.Segments)
	case RegexLine:
		return "RegexLine"
	case BlockOptional:
		if len(it.Items) == 0 {
			return "BlockOptional{}"
		}
		return fmt.Sprintf("BlockOptional{%d}", len(it.Items))
	case AnyOfBlock:
		return fmt.Sprintf("AnyOfBlock branches:%d", len(it.Branches))
	case ContainsBlock:
		return summarizeContainsBlock(it)
	default:
		return "Unknown"
	}
}

func summarizeContainsBlock(cb ContainsBlock) string {
	s := fmt.Sprintf("ContainsBlock fragments:%d", len(cb.Fragments))
	for _, f := range cb.Fragments {
		switch f.Mode {
		case ContainsStartWith:
			s += " StartWith"
		case ContainsEndWith:
			s += " EndWith"
		}
	}
	return s
}

func summarizeSegments(segs []Segment) string {
	parts := make([]string, 0, len(segs))
	for _, seg := range segs {
		parts = append(parts, summarizeSegment(seg))
	}
	return strings.Join(parts, "+")
}

func literalTagSnippet(text string) string {
	start := strings.Index(text, "<")
	if start < 0 {
		return ""
	}
	end := strings.Index(text[start:], ">")
	if end < 0 {
		return ""
	}
	return text[start : start+end+1]
}

func summarizeSegment(seg Segment) string {
	switch s := seg.(type) {
	case Literal:
		if tag := literalTagSnippet(s.Text); tag != "" {
			return "Literal " + tag
		}
		return "Literal"
	case Hint:
		return "Hint:" + s.Label
	case InlineOptional:
		return "InlineOptional"
	case InlineAnyOf:
		return fmt.Sprintf("InlineAnyOf branches:%d", len(s.Branches))
	case AnsiColor:
		return "AnsiColor " + strings.Join(s.Spec.Tokens, " ")
	case InlineRegex:
		return "InlineRegex"
	default:
		return "Unknown"
	}
}
