// Code generated by script/generate/embed-assert; DO NOT EDIT.

//go:build ignore

package assert

import (
	"fmt"
	"github.com/xhd2015/doctest/assert/legacy_v1"
	"github.com/xhd2015/doctest/assert/legacy_v2"
	"gopkg.in/yaml.v3"
	"regexp"
	"sort"
	"strings"
	"testing"
)

type parseError struct {
	pos int
	msg string
}

func (e *parseError) Error() string {
	if e.pos >= 0 {
		return fmt.Sprintf("parse error at position %d: %s", e.pos, e.msg)
	}
	return fmt.Sprintf("parse error: %s", e.msg)
}

func parseErr(pos int, format string, args ...any) error {
	return &parseError{pos: pos, msg: fmt.Sprintf(format, args...)}
}

type matchError struct {
	msg string
}

func (e *matchError) Error() string {
	return e.msg
}

func matchErr(format string, args ...any) error {
	return &matchError{msg: fmt.Sprintf(format, args...)}
}

// Match compares actual output against pattern. nil means success.
func Match(p Pattern, actual string, opts ...Option) error {
	cfg := applyOptions(opts...)
	switch p.kind {
	case patternV2:
		if cfg.mode == matchContains {
			return matchErr("MatchContains is not supported for v2 templates")
		}
		return legacy_v2.Match(p.v2pat, actual, cfg.normalizeNewlines)
	case patternV3:
		if cfg.mode == matchContains {
			return matchErr("MatchContains is not supported for v3 templates")
		}
		return matchV3(p.v3pat, actual, cfg.normalizeNewlines)
	default:
		return legacy_v1.Match(p.legacy, actual, legacy_v1.MatchConfig{
			Contains:          cfg.mode == matchContains,
			NormalizeNewlines: cfg.normalizeNewlines,
		})
	}
}

type Option interface {
	apply(*matchConfig)
}

type matchConfig struct {
	mode              matchMode
	normalizeNewlines bool
}

type matchMode int

const (
	matchExact matchMode = iota
	matchContains
)

type containsOption struct{}

func (containsOption) apply(cfg *matchConfig) {
	cfg.mode = matchContains
}

// Contains enables MatchContains mode: the template must appear as a contiguous
// ordered subregion of actual output.
func Contains() Option {
	return containsOption{}
}

type normalizeNewlinesOption struct {
	v bool
}

func (o normalizeNewlinesOption) apply(cfg *matchConfig) {
	cfg.normalizeNewlines = o.v
}

// NormalizeNewlines controls \r\n → \n normalization (default true).
func NormalizeNewlines(v bool) Option {
	return normalizeNewlinesOption{v: v}
}

func defaultMatchConfig() matchConfig {
	return matchConfig{
		mode:              matchExact,
		normalizeNewlines: true,
	}
}

func applyOptions(opts ...Option) matchConfig {
	cfg := defaultMatchConfig()
	for _, o := range opts {
		o.apply(&cfg)
	}
	return cfg
}

// Output parses template, matches actual output, and calls t.Fatal on failure.
func Output(t *testing.T, actual, template string, opts ...Option) {
	t.Helper()
	p, err := Parse(template)
	if err != nil {
		t.Fatalf("parse output template: %v", err)
	}
	if err := Match(p, actual, opts...); err != nil {
		t.Fatal(err)
	}
}

// Parse parses template text into a Pattern.
// Routing:
//   - version: 2 → legacy_v2
//   - version: 3 or YAML dialect without version (placeholder defs) → v3
//   - unknown version → parse error
//   - otherwise → legacy_v1
func Parse(template string) (Pattern, error) {
	kind, headerYAML, body, versionStr := detectDialect(template)
	switch kind {
	case dialectV2:
		v2pat, err := legacy_v2.Parse(headerYAML, body)
		if err != nil {
			return Pattern{}, err
		}
		return Pattern{kind: patternV2, v2pat: v2pat}, nil
	case dialectV3:
		v3pat, err := parseV3(headerYAML, body)
		if err != nil {
			return Pattern{}, err
		}
		return Pattern{kind: patternV3, v3pat: v3pat}, nil
	case dialectUnknownVersion:
		return Pattern{}, parseErr(0, "unknown assert template version %s", versionStr)
	default:
		legacy, err := legacy_v1.Parse(template)
		if err != nil {
			return Pattern{}, err
		}
		return Pattern{kind: patternV1, legacy: legacy}, nil
	}
}

// MustParse parses template text or panics.
func MustParse(template string) Pattern {
	p, err := Parse(template)
	if err != nil {
		panic(err)
	}
	return p
}

type patternKind int

const (
	patternV1 patternKind = iota
	patternV2
	patternV3
)

// Pattern is an immutable parsed output template (v1, v2, or v3).
type Pattern struct {
	kind   patternKind
	legacy legacy_v1.Pattern
	v2pat  legacy_v2.Pattern
	v3pat  v3Pattern
}

// PatternSummary returns a stable summary string for test introspection.
func PatternSummary(p Pattern) string {
	switch p.kind {
	case patternV2:
		return legacy_v2.PatternSummary(p.v2pat)
	case patternV3:
		return v3PatternSummary(p.v3pat)
	default:
		return legacy_v1.PatternSummary(p.legacy)
	}
}

// v3Pattern is an immutable parsed v3 output template.
// Content lines are raw Go regex full-line matches; omit markers are special.
type v3Pattern struct {
	placeholders    map[string]v3Placeholder
	items           []v3Item
	trailingNewline bool
}

type v3Placeholder struct {
	Name     string
	Type     string // "string", "number", or "regex"
	Regex    string // custom fragment when Type == "regex"
	Metadata map[string]string
}

type v3Item interface {
	isV3Item()
}

type v3RegexLine struct {
	// Pattern is a full-line RE including ^ and $ anchors, with named groups for placeholders.
	Pattern string
}

func (v3RegexLine) isV3Item() {}

type v3OmitLine struct {
	Count int
}

func (v3OmitLine) isV3Item() {}

var v3NamedColors = map[string]string{
	"bold":  "1",
	"red":   "31",
	"green": "32",
	"gray":  "90",
}

const (
	v3ColorReset          = "\x1b[0m"
	v3AnsiColorOpenPrefix = "<ansi-color"
	v3AnsiColorCloseTag   = "</ansi-color>"
	v3AnsiColorTagName    = "ansi-color"
)

type v3ColorSpec struct {
	Tokens []string
}

func v3ResolveColorOpen(spec v3ColorSpec) (string, error) {
	var b strings.Builder
	for _, tok := range spec.Tokens {
		params, err := v3ColorTokenParams(tok)
		if err != nil {
			return "", err
		}
		b.WriteString("\x1b[")
		b.WriteString(params)
		b.WriteString("m")
	}
	return b.String(), nil
}

func v3ColorTokenParams(tok string) (string, error) {
	if strings.HasPrefix(tok, "#") {
		return tok[1:], nil
	}
	params, ok := v3NamedColors[tok]
	if !ok {
		return "", parseErr(-1, "unknown color name %q; use # for raw SGR", tok)
	}
	return params, nil
}

func v3ParseColorSpec(specText string) (v3ColorSpec, error) {
	specText = strings.TrimSpace(specText)
	if specText == "" {
		return v3ColorSpec{}, parseErr(-1, "empty ansi-color specifier")
	}
	var tokens []string
	for specText != "" {
		specText = strings.TrimLeft(specText, " \t")
		if specText == "" {
			break
		}
		if specText[0] == '#' {
			end := 1
			for end < len(specText) && specText[end] != ' ' && specText[end] != '\t' {
				end++
			}
			tokens = append(tokens, specText[:end])
			specText = specText[end:]
			continue
		}
		end := 0
		for end < len(specText) && specText[end] != ' ' && specText[end] != '\t' {
			end++
		}
		name := specText[:end]
		if _, ok := v3NamedColors[name]; !ok {
			return v3ColorSpec{}, parseErr(-1, "unknown color name %q", name)
		}
		tokens = append(tokens, name)
		specText = specText[end:]
	}
	return v3ColorSpec{Tokens: tokens}, nil
}

// matchV3 compares actual output against a v3 pattern. nil means success.
// When normalizeNewlines is true, \r\n is rewritten to \n before matching.
// Same-name placeholder bindings must capture equal values across the template.
func matchV3(p v3Pattern, actual string, normalizeNewlines bool) error {
	if normalizeNewlines {
		actual = strings.ReplaceAll(actual, "\r\n", "\n")
	}
	if err := v3CheckTrailingNewline(p.trailingNewline, actual); err != nil {
		return err
	}
	lines := v3SplitActualLines(actual)
	bindings := make(map[string]string)
	cursor := 0
	for _, it := range p.items {
		n, err := v3MatchItem(it, lines, cursor, 0, bindings)
		if err != nil {
			return err
		}
		cursor = n
	}
	if cursor < len(lines) {
		return matchErr("unexpected extra output at line %d", cursor+1)
	}
	return nil
}

func v3CheckTrailingNewline(templateTrailing bool, actual string) error {
	actualTrailing := len(actual) > 0 && actual[len(actual)-1] == '\n'
	if templateTrailing != actualTrailing {
		return matchErr("output mismatch: trailing newline policy violated")
	}
	return nil
}

func v3SplitActualLines(actual string) []string {
	if actual == "" {
		return nil
	}
	body := strings.TrimSuffix(actual, "\n")
	if body == "" && strings.HasSuffix(actual, "\n") {
		return []string{""}
	}
	return strings.Split(body, "\n")
}

func v3MatchItem(it v3Item, lines []string, cursor, lineBase int, bindings map[string]string) (int, error) {
	switch x := it.(type) {
	case v3RegexLine:
		return v3MatchRegexLine(x.Pattern, lines, cursor, lineBase, bindings)
	case v3OmitLine:
		return v3MatchOmitLine(x.Count, lines, cursor, lineBase)
	default:
		return cursor, matchErr("internal error: unknown v3 item type")
	}
}

func v3MatchRegexLine(pattern string, lines []string, cursor, lineBase int, bindings map[string]string) (int, error) {
	if cursor >= len(lines) {
		return cursor, matchErr("output mismatch at line %d: regex expected a line", lineBase+cursor+1)
	}
	re, err := regexp.Compile(pattern)
	if err != nil {
		return cursor, matchErr("internal error: invalid regex: %v", err)
	}
	line := lines[cursor]
	m := re.FindStringSubmatch(line)
	if m == nil {
		return cursor, matchErr("output mismatch at line %d:\n  regex %q did not match %q", lineBase+cursor+1, pattern, line)
	}
	names := re.SubexpNames()
	for i, name := range names {
		if name == "" || i >= len(m) {
			continue
		}
		val := m[i]
		if prev, ok := bindings[name]; ok && prev != val {
			return cursor, matchErr("placeholder %s binding mismatch: previously %q, now %q", name, prev, val)
		}
		bindings[name] = val
	}
	return cursor + 1, nil
}

func v3MatchOmitLine(count int, lines []string, cursor, lineBase int) (int, error) {
	if cursor+count > len(lines) {
		return cursor, matchErr("output mismatch at line %d: omit expected %d lines, got %d", lineBase+cursor+1, count, len(lines)-cursor)
	}
	return cursor + count, nil
}

var (
	v3PlaceholderNameRE = regexp.MustCompile(`__[A-Z][A-Z0-9_]*__`)
	v3OmitLineRE        = regexp.MustCompile(`^\.\.\.\s*(\d+)\s*lines\s+omitted\s*\.\.\.$`)
	v3OmitIntentRE      = regexp.MustCompile(`^\.\.\.\s*.+\s+lines\s+omitted\s*\.\.\.$`)
)

// dialectKind classifies a template for facade routing.
type dialectKind int

const (
	dialectNone dialectKind = iota // no YAML assert dialect → legacy_v1
	dialectV2
	dialectV3
	dialectUnknownVersion
)

// detectDialect classifies template routing:
//   - version: 2 → dialectV2
//   - version: 3 → dialectV3
//   - unknown version → dialectUnknownVersion (caller errors)
//   - YAML header with placeholder keys, no version → dialectV3 (default)
//   - otherwise → dialectNone (legacy_v1), including non-dialect --- frontmatter
func detectDialect(template string) (kind dialectKind, headerYAML, body string, versionStr string) {
	template = v3TrimLeadingBlankLinesBeforeHeader(template)
	if !strings.HasPrefix(template, "---") {
		return dialectNone, "", template, ""
	}
	rest := template[3:]
	if strings.HasPrefix(rest, "\r\n") {
		rest = rest[2:]
	} else if strings.HasPrefix(rest, "\n") {
		rest = rest[1:]
	} else {
		return dialectNone, "", template, ""
	}
	closeIdx := strings.Index(rest, "\n---")
	if closeIdx < 0 {
		return dialectNone, "", template, ""
	}
	headerYAML = rest[:closeIdx]
	body = rest[closeIdx+4:]
	if strings.HasPrefix(body, "\r\n") {
		body = body[2:]
	} else if strings.HasPrefix(body, "\n") {
		body = body[1:]
	}

	var raw map[string]any
	if err := yaml.Unmarshal([]byte(headerYAML), &raw); err != nil {
		return dialectNone, "", template, ""
	}

	version, hasVersion := raw["version"]
	if hasVersion {
		versionStr = fmt.Sprint(version)
		// Normalize float-ish YAML ints (e.g. 2.0).
		switch v := version.(type) {
		case int:
			versionStr = fmt.Sprintf("%d", v)
		case int64:
			versionStr = fmt.Sprintf("%d", v)
		case float64:
			if v == float64(int(v)) {
				versionStr = fmt.Sprintf("%d", int(v))
			}
		}
		switch versionStr {
		case "2":
			return dialectV2, headerYAML, body, versionStr
		case "3":
			return dialectV3, headerYAML, body, versionStr
		default:
			return dialectUnknownVersion, headerYAML, body, versionStr
		}
	}

	// No version key: default to v3 only for YAML dialect with placeholder defs.
	// Plain frontmatter without placeholders stays on legacy_v1 (v2 missing-version leaf).
	for key := range raw {
		if v3PlaceholderNameRE.MatchString(key) {
			return dialectV3, headerYAML, body, ""
		}
	}
	return dialectNone, "", template, ""
}

// parseV3 parses a v3 YAML header and template body into a v3Pattern.
func parseV3(headerYAML, body string) (v3Pattern, error) {
	var raw map[string]any
	if err := yaml.Unmarshal([]byte(headerYAML), &raw); err != nil {
		return v3Pattern{}, parseErr(0, "invalid YAML header: %v", err)
	}

	placeholders := make(map[string]v3Placeholder)
	for key, val := range raw {
		if key == "version" {
			continue
		}
		if !v3PlaceholderNameRE.MatchString(key) {
			continue
		}
		text, ok := val.(string)
		if !ok {
			return v3Pattern{}, parseErr(0, "invalid placeholder definition for %s", key)
		}
		ph, err := v3ParsePlaceholderDef(key, text)
		if err != nil {
			return v3Pattern{}, err
		}
		placeholders[key] = ph
	}

	lines, trailing := v3SplitTemplateLines(body)
	var items []v3Item
	for i, line := range lines {
		pos := v3LineOffset(lines, i)
		if v3OmitIntentRE.MatchString(strings.TrimSpace(line)) {
			count, ok := v3IsOmitLine(line)
			if !ok {
				return v3Pattern{}, parseErr(pos, "invalid omit marker syntax")
			}
			items = append(items, v3OmitLine{Count: count})
			continue
		}
		it, err := v3ParseContentLine(line, pos, placeholders)
		if err != nil {
			return v3Pattern{}, err
		}
		items = append(items, it)
	}

	if err := v3ValidatePlaceholdersUsed(body, placeholders); err != nil {
		return v3Pattern{}, err
	}

	return v3Pattern{
		placeholders:    placeholders,
		items:           items,
		trailingNewline: trailing,
	}, nil
}

func v3ParsePlaceholderDef(name, raw string) (v3Placeholder, error) {
	parts := v3SplitCompactParts(raw)
	if len(parts) == 0 {
		return v3Placeholder{}, parseErr(0, "empty placeholder definition for %s", name)
	}

	meta := make(map[string]string)
	var typ string
	var customRE string
	for _, part := range parts {
		eq := strings.Index(part, "=")
		if eq <= 0 {
			break
		}
		key := strings.TrimSpace(part[:eq])
		val := strings.TrimSpace(part[eq+1:])
		if key == "" || val == "" {
			break
		}
		switch key {
		case "type":
			typ = val
		case "regex":
			customRE = val
		default:
			meta[key] = val
		}
	}

	if typ != "" && customRE != "" {
		return v3Placeholder{}, parseErr(0, "placeholder %s cannot set both type= and regex=", name)
	}
	if typ == "" && customRE == "" {
		return v3Placeholder{}, parseErr(0, "placeholder %s missing type or regex", name)
	}

	shortName := strings.Trim(name, "_")

	if customRE != "" {
		if _, err := regexp.Compile(customRE); err != nil {
			return v3Placeholder{}, parseErr(0, "invalid regex for %s: %v", name, err)
		}
		return v3Placeholder{Name: shortName, Type: "regex", Regex: customRE, Metadata: meta}, nil
	}

	if typ != "string" && typ != "number" {
		return v3Placeholder{}, parseErr(0, "unknown placeholder type %q for %s", typ, name)
	}
	return v3Placeholder{Name: shortName, Type: typ, Metadata: meta}, nil
}

func v3SplitCompactParts(raw string) []string {
	var parts []string
	var cur strings.Builder
	depth := 0
	for _, ch := range raw {
		switch ch {
		case '(':
			depth++
			cur.WriteRune(ch)
		case ')':
			if depth > 0 {
				depth--
			}
			cur.WriteRune(ch)
		case ',':
			if depth == 0 {
				parts = append(parts, strings.TrimSpace(cur.String()))
				cur.Reset()
				continue
			}
			cur.WriteRune(ch)
		default:
			cur.WriteRune(ch)
		}
	}
	if s := strings.TrimSpace(cur.String()); s != "" {
		parts = append(parts, s)
	}
	return parts
}

func v3ValidatePlaceholdersUsed(body string, defined map[string]v3Placeholder) error {
	used := v3PlaceholderNameRE.FindAllString(body, -1)
	seen := make(map[string]bool)
	for _, name := range used {
		if seen[name] {
			continue
		}
		seen[name] = true
		if _, ok := defined[name]; !ok {
			short := strings.Trim(name, "_")
			return parseErr(0, "undefined placeholder __%s__", short)
		}
	}
	return nil
}

func v3IsOmitLine(line string) (int, bool) {
	m := v3OmitLineRE.FindStringSubmatch(strings.TrimSpace(line))
	if m == nil {
		return 0, false
	}
	var count int
	for _, ch := range m[1] {
		count = count*10 + int(ch-'0')
	}
	return count, true
}

// v3ParseContentLine builds a full-line raw RE with named capture groups for placeholders.
// Color spans keep CSI structure with QuoteMeta on open/inner/reset; outside tags stay raw RE.
func v3ParseContentLine(line string, pos int, placeholders map[string]v3Placeholder) (v3Item, error) {
	body, err := v3BuildRegexBody(line, pos, placeholders)
	if err != nil {
		return nil, err
	}
	pattern := "^" + body + "$"
	if _, err := regexp.Compile(pattern); err != nil {
		return nil, parseErr(pos, "invalid regex: %v", err)
	}
	return v3RegexLine{Pattern: pattern}, nil
}

func v3BuildRegexBody(line string, pos int, placeholders map[string]v3Placeholder) (string, error) {
	var b strings.Builder
	// Track which placeholder names already introduced a named group on this line
	// so repeats use backreferences (?P=NAME) — Go forbids duplicate named groups.
	namedIntroduced := make(map[string]bool)
	i := 0
	for i < len(line) {
		if strings.HasPrefix(line[i:], v3AnsiColorOpenPrefix) {
			openEnd := strings.Index(line[i:], ">")
			if openEnd < 0 {
				return "", parseErr(pos+i, "unclosed <ansi-color>")
			}
			openEnd += i
			openTag := line[i+1 : openEnd]
			if !strings.HasPrefix(openTag, v3AnsiColorTagName) {
				return "", parseErr(pos+i, "expected <ansi-color>")
			}
			specText := strings.TrimSpace(openTag[len(v3AnsiColorTagName):])
			spec, err := v3ParseColorSpec(specText)
			if err != nil {
				return "", err
			}
			closeIdx := strings.Index(line[openEnd+1:], v3AnsiColorCloseTag)
			if closeIdx < 0 {
				return "", parseErr(pos+i, "unclosed <ansi-color>")
			}
			inner := line[openEnd+1 : openEnd+1+closeIdx]
			if inner == "" {
				return "", parseErr(pos+i, "empty ansi-color inner text")
			}
			open, err := v3ResolveColorOpen(spec)
			if err != nil {
				return "", err
			}
			// CSI structure kept; inner text QuoteMeta'd (literal dots etc.).
			b.WriteString(regexp.QuoteMeta(open))
			b.WriteString(regexp.QuoteMeta(inner))
			b.WriteString(regexp.QuoteMeta(v3ColorReset))
			i = openEnd + 1 + closeIdx + len(v3AnsiColorCloseTag)
			continue
		}

		nextPH := v3PlaceholderNameRE.FindStringIndex(line[i:])
		nextColor := strings.Index(line[i:], v3AnsiColorOpenPrefix)
		litEnd := len(line)
		if nextPH != nil {
			litEnd = i + nextPH[0]
		}
		if nextColor >= 0 && i+nextColor < litEnd {
			litEnd = i + nextColor
		}
		if litEnd > i {
			// Raw RE syntax outside placeholders and color tags.
			b.WriteString(line[i:litEnd])
			i = litEnd
			continue
		}
		if nextPH != nil {
			full := line[i+nextPH[0] : i+nextPH[1]]
			ph, ok := placeholders[full]
			if !ok {
				short := strings.Trim(full, "_")
				return "", parseErr(pos+i, "undefined placeholder __%s__", short)
			}
			sub, err := v3PlaceholderSubpattern(ph)
			if err != nil {
				return "", err
			}
			if namedIntroduced[ph.Name] {
				// Same-name binding within the line via named backreference.
				b.WriteString("(?P=")
				b.WriteString(ph.Name)
				b.WriteString(")")
			} else {
				b.WriteString("(?P<")
				b.WriteString(ph.Name)
				b.WriteString(">")
				b.WriteString(sub)
				b.WriteString(")")
				namedIntroduced[ph.Name] = true
			}
			i += nextPH[1]
			continue
		}
		break
	}
	return b.String(), nil
}

func v3PlaceholderSubpattern(ph v3Placeholder) (string, error) {
	switch ph.Type {
	case "string":
		return `[^\n]*?`, nil
	case "number":
		return `-?\d+(?:\.\d+)?`, nil
	case "regex":
		if ph.Regex == "" {
			return "", parseErr(-1, "placeholder %s missing regex fragment", ph.Name)
		}
		return ph.Regex, nil
	default:
		return "", parseErr(-1, "unknown placeholder type %q", ph.Type)
	}
}

func v3SplitTemplateLines(s string) ([]string, bool) {
	trailing := strings.HasSuffix(s, "\n")
	if s == "" {
		return nil, trailing
	}
	body := strings.TrimSuffix(s, "\n")
	if body == "" && trailing {
		return []string{""}, trailing
	}
	return strings.Split(body, "\n"), trailing
}

func v3LineOffset(lines []string, lineIdx int) int {
	if lineIdx <= 0 {
		return 0
	}
	offset := 0
	for i := 0; i < lineIdx && i < len(lines); i++ {
		offset += len(lines[i]) + 1
	}
	return offset
}

func v3TrimLeadingBlankLinesBeforeHeader(s string) string {
	for len(s) > 0 {
		if strings.HasPrefix(s, "---") {
			return s
		}
		s = strings.TrimLeft(s, " \t")
		if strings.HasPrefix(s, "---") {
			return s
		}
		if strings.HasPrefix(s, "\r\n") {
			s = s[2:]
			continue
		}
		if strings.HasPrefix(s, "\n") {
			s = s[1:]
			continue
		}
		return s
	}
	return s
}

// v3PatternSummary returns a stable summary string for v3 pattern introspection.
func v3PatternSummary(p v3Pattern) string {
	var parts []string
	if len(p.placeholders) > 0 {
		parts = append(parts, v3SummarizePlaceholders(p.placeholders))
	}
	for _, it := range p.items {
		parts = append(parts, v3SummarizeItem(it))
	}
	return v3CombineSummaryParts(parts)
}

func v3SummarizePlaceholders(placeholders map[string]v3Placeholder) string {
	names := make([]string, 0, len(placeholders))
	for _, ph := range placeholders {
		names = append(names, ph.Name)
	}
	sort.Strings(names)
	var defs []string
	for _, name := range names {
		for _, ph := range placeholders {
			if ph.Name == name {
				defs = append(defs, v3SummarizePlaceholder(ph))
				break
			}
		}
	}
	return "Placeholders:" + strings.Join(defs, ",")
}

func v3SummarizePlaceholder(ph v3Placeholder) string {
	s := fmt.Sprintf("%s{%s", ph.Name, ph.Type)
	keys := make([]string, 0, len(ph.Metadata))
	for k := range ph.Metadata {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		s += "," + k + "=" + ph.Metadata[k]
	}
	if ph.Type == "regex" && ph.Regex != "" {
		s += ",regex=" + ph.Regex
	}
	s += "}"
	return s
}

func v3SummarizeItem(it v3Item) string {
	switch x := it.(type) {
	case v3RegexLine:
		return "RegexLine"
	case v3OmitLine:
		return fmt.Sprintf("OmitLine{%d}", x.Count)
	default:
		return "Unknown"
	}
}

func v3CombineSummaryParts(parts []string) string {
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "+")
}
