name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.0
    steps:
      - uses: actions/checkout@v4
      - name: Go test
        run: go test -v ./...

      - name: Build doctest
        run: go build -o doctest ./cmd/doctest
      - name: Doctest
        run: ./doctest test -v ./...
